/*
Integration API reference docs

Use the Integration API to push data to and retrieve data from Talon.One in real time. For more background information about this API, see [Integration API overview](/docs/dev/integration-api/overview)  For example, use this API to share shopping cart information as a session with Talon.One and evaluate promotion rules. You can also create custom events to track specific actions that do not fit into the session data model.  Ensure you [authenticate](#section/Authentication) to make requests to the API.  <div class=\"redoc-section\">   <p class=\"title\">Are you looking for a different API?</p>    If you need the API to:    - Interact with the Campaign Manager for backoffice operations, see [the Management API reference docs](https://docs.talon.one/management-api).   - Integrate with Talon.One from a CEP or CDP platform, see [the Third-party API reference docs](https://docs.talon.one/third-party-api).  </div>  # Authentication  <SecurityDefinitions /> 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
)

// RoleMembership struct for RoleMembership
type RoleMembership struct {
	// ID of role.
	RoleID int32 `json:"RoleID"`
	// ID of User.
	UserID int32 `json:"UserID"`
}

// NewRoleMembership instantiates a new RoleMembership object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoleMembership(roleID int32, userID int32) *RoleMembership {
	this := RoleMembership{}
	this.RoleID = roleID
	this.UserID = userID
	return &this
}

// NewRoleMembershipWithDefaults instantiates a new RoleMembership object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoleMembershipWithDefaults() *RoleMembership {
	this := RoleMembership{}
	return &this
}

// GetRoleID returns the RoleID field value
func (o *RoleMembership) GetRoleID() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RoleID
}

// GetRoleIDOk returns a tuple with the RoleID field value
// and a boolean to check if the value has been set.
func (o *RoleMembership) GetRoleIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RoleID, true
}

// SetRoleID sets field value
func (o *RoleMembership) SetRoleID(v int32) {
	o.RoleID = v
}

// GetUserID returns the UserID field value
func (o *RoleMembership) GetUserID() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.UserID
}

// GetUserIDOk returns a tuple with the UserID field value
// and a boolean to check if the value has been set.
func (o *RoleMembership) GetUserIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserID, true
}

// SetUserID sets field value
func (o *RoleMembership) SetUserID(v int32) {
	o.UserID = v
}

func (o RoleMembership) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["RoleID"] = o.RoleID
	}
	if true {
		toSerialize["UserID"] = o.UserID
	}
	return json.Marshal(toSerialize)
}

type NullableRoleMembership struct {
	value *RoleMembership
	isSet bool
}

func (v NullableRoleMembership) Get() *RoleMembership {
	return v.value
}

func (v *NullableRoleMembership) Set(val *RoleMembership) {
	v.value = val
	v.isSet = true
}

func (v NullableRoleMembership) IsSet() bool {
	return v.isSet
}

func (v *NullableRoleMembership) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoleMembership(val *RoleMembership) *NullableRoleMembership {
	return &NullableRoleMembership{value: val, isSet: true}
}

func (v NullableRoleMembership) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoleMembership) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


