/*
Integration API reference docs

Use the Integration API to push data to and retrieve data from Talon.One in real time. For more background information about this API, see [Integration API overview](/docs/dev/integration-api/overview)  For example, use this API to share shopping cart information as a session with Talon.One and evaluate promotion rules. You can also create custom events to track specific actions that do not fit into the session data model.  Ensure you [authenticate](#section/Authentication) to make requests to the API.  <div class=\"redoc-section\">   <p class=\"title\">Are you looking for a different API?</p>    If you need the API to:    - Interact with the Campaign Manager for backoffice operations, see [the Management API reference docs](https://docs.talon.one/management-api).   - Integrate with Talon.One from a CEP or CDP platform, see [the Third-party API reference docs](https://docs.talon.one/third-party-api).  </div>  # Authentication  <SecurityDefinitions /> 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
)

// LoyaltyProgramBalance The balance in a Loyalty Program for some Customer.
type LoyaltyProgramBalance struct {
	// Sum of currently active points.
	CurrentBalance float32 `json:"currentBalance"`
	// Sum of pending points.
	PendingBalance float32 `json:"pendingBalance"`
	// Sum of expired points.
	ExpiredBalance float32 `json:"expiredBalance"`
	// Sum of spent points.
	SpentBalance float32 `json:"spentBalance"`
	// Sum of currently active points, including points added and deducted in open sessions.
	TentativeCurrentBalance float32 `json:"tentativeCurrentBalance"`
}

// NewLoyaltyProgramBalance instantiates a new LoyaltyProgramBalance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoyaltyProgramBalance(currentBalance float32, pendingBalance float32, expiredBalance float32, spentBalance float32, tentativeCurrentBalance float32) *LoyaltyProgramBalance {
	this := LoyaltyProgramBalance{}
	this.CurrentBalance = currentBalance
	this.PendingBalance = pendingBalance
	this.ExpiredBalance = expiredBalance
	this.SpentBalance = spentBalance
	this.TentativeCurrentBalance = tentativeCurrentBalance
	return &this
}

// NewLoyaltyProgramBalanceWithDefaults instantiates a new LoyaltyProgramBalance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoyaltyProgramBalanceWithDefaults() *LoyaltyProgramBalance {
	this := LoyaltyProgramBalance{}
	return &this
}

// GetCurrentBalance returns the CurrentBalance field value
func (o *LoyaltyProgramBalance) GetCurrentBalance() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.CurrentBalance
}

// GetCurrentBalanceOk returns a tuple with the CurrentBalance field value
// and a boolean to check if the value has been set.
func (o *LoyaltyProgramBalance) GetCurrentBalanceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrentBalance, true
}

// SetCurrentBalance sets field value
func (o *LoyaltyProgramBalance) SetCurrentBalance(v float32) {
	o.CurrentBalance = v
}

// GetPendingBalance returns the PendingBalance field value
func (o *LoyaltyProgramBalance) GetPendingBalance() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.PendingBalance
}

// GetPendingBalanceOk returns a tuple with the PendingBalance field value
// and a boolean to check if the value has been set.
func (o *LoyaltyProgramBalance) GetPendingBalanceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PendingBalance, true
}

// SetPendingBalance sets field value
func (o *LoyaltyProgramBalance) SetPendingBalance(v float32) {
	o.PendingBalance = v
}

// GetExpiredBalance returns the ExpiredBalance field value
func (o *LoyaltyProgramBalance) GetExpiredBalance() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ExpiredBalance
}

// GetExpiredBalanceOk returns a tuple with the ExpiredBalance field value
// and a boolean to check if the value has been set.
func (o *LoyaltyProgramBalance) GetExpiredBalanceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiredBalance, true
}

// SetExpiredBalance sets field value
func (o *LoyaltyProgramBalance) SetExpiredBalance(v float32) {
	o.ExpiredBalance = v
}

// GetSpentBalance returns the SpentBalance field value
func (o *LoyaltyProgramBalance) GetSpentBalance() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.SpentBalance
}

// GetSpentBalanceOk returns a tuple with the SpentBalance field value
// and a boolean to check if the value has been set.
func (o *LoyaltyProgramBalance) GetSpentBalanceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SpentBalance, true
}

// SetSpentBalance sets field value
func (o *LoyaltyProgramBalance) SetSpentBalance(v float32) {
	o.SpentBalance = v
}

// GetTentativeCurrentBalance returns the TentativeCurrentBalance field value
func (o *LoyaltyProgramBalance) GetTentativeCurrentBalance() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.TentativeCurrentBalance
}

// GetTentativeCurrentBalanceOk returns a tuple with the TentativeCurrentBalance field value
// and a boolean to check if the value has been set.
func (o *LoyaltyProgramBalance) GetTentativeCurrentBalanceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TentativeCurrentBalance, true
}

// SetTentativeCurrentBalance sets field value
func (o *LoyaltyProgramBalance) SetTentativeCurrentBalance(v float32) {
	o.TentativeCurrentBalance = v
}

func (o LoyaltyProgramBalance) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["currentBalance"] = o.CurrentBalance
	}
	if true {
		toSerialize["pendingBalance"] = o.PendingBalance
	}
	if true {
		toSerialize["expiredBalance"] = o.ExpiredBalance
	}
	if true {
		toSerialize["spentBalance"] = o.SpentBalance
	}
	if true {
		toSerialize["tentativeCurrentBalance"] = o.TentativeCurrentBalance
	}
	return json.Marshal(toSerialize)
}

type NullableLoyaltyProgramBalance struct {
	value *LoyaltyProgramBalance
	isSet bool
}

func (v NullableLoyaltyProgramBalance) Get() *LoyaltyProgramBalance {
	return v.value
}

func (v *NullableLoyaltyProgramBalance) Set(val *LoyaltyProgramBalance) {
	v.value = val
	v.isSet = true
}

func (v NullableLoyaltyProgramBalance) IsSet() bool {
	return v.isSet
}

func (v *NullableLoyaltyProgramBalance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoyaltyProgramBalance(val *LoyaltyProgramBalance) *NullableLoyaltyProgramBalance {
	return &NullableLoyaltyProgramBalance{value: val, isSet: true}
}

func (v NullableLoyaltyProgramBalance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoyaltyProgramBalance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


