/*
Integration API reference docs

Use the Integration API to push data to and retrieve data from Talon.One in real time. For more background information about this API, see [Integration API overview](/docs/dev/integration-api/overview)  For example, use this API to share shopping cart information as a session with Talon.One and evaluate promotion rules. You can also create custom events to track specific actions that do not fit into the session data model.  Ensure you [authenticate](#section/Authentication) to make requests to the API.  <div class=\"redoc-section\">   <p class=\"title\">Are you looking for a different API?</p>    If you need the API to:    - Interact with the Campaign Manager for backoffice operations, see [the Management API reference docs](https://docs.talon.one/management-api).   - Integrate with Talon.One from a CEP or CDP platform, see [the Third-party API reference docs](https://docs.talon.one/third-party-api).  </div>  # Authentication  <SecurityDefinitions /> 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
)

// CampaignSetNode struct for CampaignSetNode
type CampaignSetNode struct {
	Type string `json:"type"`
}

// NewCampaignSetNode instantiates a new CampaignSetNode object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCampaignSetNode(type_ string) *CampaignSetNode {
	this := CampaignSetNode{}
	this.Type = type_
	return &this
}

// NewCampaignSetNodeWithDefaults instantiates a new CampaignSetNode object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCampaignSetNodeWithDefaults() *CampaignSetNode {
	this := CampaignSetNode{}
	return &this
}

// GetType returns the Type field value
func (o *CampaignSetNode) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CampaignSetNode) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CampaignSetNode) SetType(v string) {
	o.Type = v
}

func (o CampaignSetNode) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableCampaignSetNode struct {
	value *CampaignSetNode
	isSet bool
}

func (v NullableCampaignSetNode) Get() *CampaignSetNode {
	return v.value
}

func (v *NullableCampaignSetNode) Set(val *CampaignSetNode) {
	v.value = val
	v.isSet = true
}

func (v NullableCampaignSetNode) IsSet() bool {
	return v.isSet
}

func (v *NullableCampaignSetNode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCampaignSetNode(val *CampaignSetNode) *NullableCampaignSetNode {
	return &NullableCampaignSetNode{value: val, isSet: true}
}

func (v NullableCampaignSetNode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCampaignSetNode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


