/*
Integration API reference docs

Use the Integration API to push data to and retrieve data from Talon.One in real time. For more background information about this API, see [Integration API overview](/docs/dev/integration-api/overview)  For example, use this API to share shopping cart information as a session with Talon.One and evaluate promotion rules. You can also create custom events to track specific actions that do not fit into the session data model.  Ensure you [authenticate](#section/Authentication) to make requests to the API.  <div class=\"redoc-section\">   <p class=\"title\">Are you looking for a different API?</p>    If you need the API to:    - Interact with the Campaign Manager for backoffice operations, see [the Management API reference docs](https://docs.talon.one/management-api).   - Integrate with Talon.One from a CEP or CDP platform, see [the Third-party API reference docs](https://docs.talon.one/third-party-api).  </div>  # Authentication  <SecurityDefinitions /> 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
	"time"
)

// Audience 
type Audience struct {
	// The ID of the account that owns this entity.
	AccountId int32 `json:"accountId"`
	// Unique ID for this entity. Not to be confused with the Integration ID, which is set by your integration layer and used in most endpoints.
	Id int32 `json:"id"`
	// The exact moment this entity was created.
	Created time.Time `json:"created"`
	// The human-friendly display name for this audience.
	Name string `json:"name"`
	// The Talon.One-supported [3rd-party platform](https://docs.talon.one/docs/dev/technology-partners/overview) that this audience was created in.  For example, `mParticle`, `Segment`, `Selligent`, `Braze`, or `Iterable`.  **Note:** If you do not integrate with any of these platforms, do not use this property. 
	Integration *string `json:"integration,omitempty"`
	// The ID of this audience in the third-party integration.  **Note:** To create an audience that doesn't come from a 3rd party platform, do not use this property. 
	IntegrationId *string `json:"integrationId,omitempty"`
	// Indicates if this is a live or sandbox Application.
	Sandbox *bool `json:"sandbox,omitempty"`
	// Determines if this audience is a 3rd party audience or not.
	CreatedIn3rdParty *bool `json:"createdIn3rdParty,omitempty"`
}

// NewAudience instantiates a new Audience object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAudience(accountId int32, id int32, created time.Time, name string) *Audience {
	this := Audience{}
	this.AccountId = accountId
	this.Id = id
	this.Created = created
	this.Name = name
	return &this
}

// NewAudienceWithDefaults instantiates a new Audience object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAudienceWithDefaults() *Audience {
	this := Audience{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *Audience) GetAccountId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *Audience) GetAccountIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *Audience) SetAccountId(v int32) {
	o.AccountId = v
}

// GetId returns the Id field value
func (o *Audience) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Audience) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Audience) SetId(v int32) {
	o.Id = v
}

// GetCreated returns the Created field value
func (o *Audience) GetCreated() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *Audience) GetCreatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *Audience) SetCreated(v time.Time) {
	o.Created = v
}

// GetName returns the Name field value
func (o *Audience) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Audience) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Audience) SetName(v string) {
	o.Name = v
}

// GetIntegration returns the Integration field value if set, zero value otherwise.
func (o *Audience) GetIntegration() string {
	if o == nil || o.Integration == nil {
		var ret string
		return ret
	}
	return *o.Integration
}

// GetIntegrationOk returns a tuple with the Integration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Audience) GetIntegrationOk() (*string, bool) {
	if o == nil || o.Integration == nil {
		return nil, false
	}
	return o.Integration, true
}

// HasIntegration returns a boolean if a field has been set.
func (o *Audience) HasIntegration() bool {
	if o != nil && o.Integration != nil {
		return true
	}

	return false
}

// SetIntegration gets a reference to the given string and assigns it to the Integration field.
func (o *Audience) SetIntegration(v string) {
	o.Integration = &v
}

// GetIntegrationId returns the IntegrationId field value if set, zero value otherwise.
func (o *Audience) GetIntegrationId() string {
	if o == nil || o.IntegrationId == nil {
		var ret string
		return ret
	}
	return *o.IntegrationId
}

// GetIntegrationIdOk returns a tuple with the IntegrationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Audience) GetIntegrationIdOk() (*string, bool) {
	if o == nil || o.IntegrationId == nil {
		return nil, false
	}
	return o.IntegrationId, true
}

// HasIntegrationId returns a boolean if a field has been set.
func (o *Audience) HasIntegrationId() bool {
	if o != nil && o.IntegrationId != nil {
		return true
	}

	return false
}

// SetIntegrationId gets a reference to the given string and assigns it to the IntegrationId field.
func (o *Audience) SetIntegrationId(v string) {
	o.IntegrationId = &v
}

// GetSandbox returns the Sandbox field value if set, zero value otherwise.
func (o *Audience) GetSandbox() bool {
	if o == nil || o.Sandbox == nil {
		var ret bool
		return ret
	}
	return *o.Sandbox
}

// GetSandboxOk returns a tuple with the Sandbox field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Audience) GetSandboxOk() (*bool, bool) {
	if o == nil || o.Sandbox == nil {
		return nil, false
	}
	return o.Sandbox, true
}

// HasSandbox returns a boolean if a field has been set.
func (o *Audience) HasSandbox() bool {
	if o != nil && o.Sandbox != nil {
		return true
	}

	return false
}

// SetSandbox gets a reference to the given bool and assigns it to the Sandbox field.
func (o *Audience) SetSandbox(v bool) {
	o.Sandbox = &v
}

// GetCreatedIn3rdParty returns the CreatedIn3rdParty field value if set, zero value otherwise.
func (o *Audience) GetCreatedIn3rdParty() bool {
	if o == nil || o.CreatedIn3rdParty == nil {
		var ret bool
		return ret
	}
	return *o.CreatedIn3rdParty
}

// GetCreatedIn3rdPartyOk returns a tuple with the CreatedIn3rdParty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Audience) GetCreatedIn3rdPartyOk() (*bool, bool) {
	if o == nil || o.CreatedIn3rdParty == nil {
		return nil, false
	}
	return o.CreatedIn3rdParty, true
}

// HasCreatedIn3rdParty returns a boolean if a field has been set.
func (o *Audience) HasCreatedIn3rdParty() bool {
	if o != nil && o.CreatedIn3rdParty != nil {
		return true
	}

	return false
}

// SetCreatedIn3rdParty gets a reference to the given bool and assigns it to the CreatedIn3rdParty field.
func (o *Audience) SetCreatedIn3rdParty(v bool) {
	o.CreatedIn3rdParty = &v
}

func (o Audience) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["accountId"] = o.AccountId
	}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["created"] = o.Created
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.Integration != nil {
		toSerialize["integration"] = o.Integration
	}
	if o.IntegrationId != nil {
		toSerialize["integrationId"] = o.IntegrationId
	}
	if o.Sandbox != nil {
		toSerialize["sandbox"] = o.Sandbox
	}
	if o.CreatedIn3rdParty != nil {
		toSerialize["createdIn3rdParty"] = o.CreatedIn3rdParty
	}
	return json.Marshal(toSerialize)
}

type NullableAudience struct {
	value *Audience
	isSet bool
}

func (v NullableAudience) Get() *Audience {
	return v.value
}

func (v *NullableAudience) Set(val *Audience) {
	v.value = val
	v.isSet = true
}

func (v NullableAudience) IsSet() bool {
	return v.isSet
}

func (v *NullableAudience) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAudience(val *Audience) *NullableAudience {
	return &NullableAudience{value: val, isSet: true}
}

func (v NullableAudience) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAudience) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


