/*
Integration API reference docs

Use the Integration API to push data to and retrieve data from Talon.One in real time. For more background information about this API, see [Integration API overview](/docs/dev/integration-api/overview)  For example, use this API to share shopping cart information as a session with Talon.One and evaluate promotion rules. You can also create custom events to track specific actions that do not fit into the session data model.  Ensure you [authenticate](#section/Authentication) to make requests to the API.  <div class=\"redoc-section\">   <p class=\"title\">Are you looking for a different API?</p>    If you need the API to:    - Interact with the Campaign Manager for backoffice operations, see [the Management API reference docs](https://docs.talon.one/management-api).   - Integrate with Talon.One from a CEP or CDP platform, see [the Third-party API reference docs](https://docs.talon.one/third-party-api).  </div>  # Authentication  <SecurityDefinitions /> 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
	"time"
)

// NewCouponsForMultipleRecipients 
type NewCouponsForMultipleRecipients struct {
	// The number of times the coupon code can be redeemed. `0` means unlimited redemptions but any campaign usage limits will still apply. 
	UsageLimit int32 `json:"usageLimit"`
	// The amount of discounts that can be given with this coupon code. 
	DiscountLimit *float32 `json:"discountLimit,omitempty"`
	// Timestamp at which point the coupon becomes valid.
	StartDate *time.Time `json:"startDate,omitempty"`
	// Expiry date of the coupon. Coupon never expires if this is omitted, zero, or negative.
	ExpiryDate *time.Time `json:"expiryDate,omitempty"`
	// Arbitrary properties associated with this item.
	Attributes map[string]interface{} `json:"attributes,omitempty"`
	// The integration IDs for recipients.
	RecipientsIntegrationIds []string `json:"recipientsIntegrationIds"`
	// List of characters used to generate the random parts of a code. By default, the list of characters is equivalent to the `[A-Z, 0-9]` regular expression. 
	ValidCharacters []string `json:"validCharacters,omitempty"`
	// The pattern used to generate coupon codes. The character `#` is a placeholder and is replaced by a random character from the `validCharacters` set. 
	CouponPattern *string `json:"couponPattern,omitempty"`
}

// NewNewCouponsForMultipleRecipients instantiates a new NewCouponsForMultipleRecipients object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNewCouponsForMultipleRecipients(usageLimit int32, recipientsIntegrationIds []string) *NewCouponsForMultipleRecipients {
	this := NewCouponsForMultipleRecipients{}
	this.UsageLimit = usageLimit
	this.RecipientsIntegrationIds = recipientsIntegrationIds
	return &this
}

// NewNewCouponsForMultipleRecipientsWithDefaults instantiates a new NewCouponsForMultipleRecipients object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNewCouponsForMultipleRecipientsWithDefaults() *NewCouponsForMultipleRecipients {
	this := NewCouponsForMultipleRecipients{}
	return &this
}

// GetUsageLimit returns the UsageLimit field value
func (o *NewCouponsForMultipleRecipients) GetUsageLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.UsageLimit
}

// GetUsageLimitOk returns a tuple with the UsageLimit field value
// and a boolean to check if the value has been set.
func (o *NewCouponsForMultipleRecipients) GetUsageLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UsageLimit, true
}

// SetUsageLimit sets field value
func (o *NewCouponsForMultipleRecipients) SetUsageLimit(v int32) {
	o.UsageLimit = v
}

// GetDiscountLimit returns the DiscountLimit field value if set, zero value otherwise.
func (o *NewCouponsForMultipleRecipients) GetDiscountLimit() float32 {
	if o == nil || o.DiscountLimit == nil {
		var ret float32
		return ret
	}
	return *o.DiscountLimit
}

// GetDiscountLimitOk returns a tuple with the DiscountLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewCouponsForMultipleRecipients) GetDiscountLimitOk() (*float32, bool) {
	if o == nil || o.DiscountLimit == nil {
		return nil, false
	}
	return o.DiscountLimit, true
}

// HasDiscountLimit returns a boolean if a field has been set.
func (o *NewCouponsForMultipleRecipients) HasDiscountLimit() bool {
	if o != nil && o.DiscountLimit != nil {
		return true
	}

	return false
}

// SetDiscountLimit gets a reference to the given float32 and assigns it to the DiscountLimit field.
func (o *NewCouponsForMultipleRecipients) SetDiscountLimit(v float32) {
	o.DiscountLimit = &v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise.
func (o *NewCouponsForMultipleRecipients) GetStartDate() time.Time {
	if o == nil || o.StartDate == nil {
		var ret time.Time
		return ret
	}
	return *o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewCouponsForMultipleRecipients) GetStartDateOk() (*time.Time, bool) {
	if o == nil || o.StartDate == nil {
		return nil, false
	}
	return o.StartDate, true
}

// HasStartDate returns a boolean if a field has been set.
func (o *NewCouponsForMultipleRecipients) HasStartDate() bool {
	if o != nil && o.StartDate != nil {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given time.Time and assigns it to the StartDate field.
func (o *NewCouponsForMultipleRecipients) SetStartDate(v time.Time) {
	o.StartDate = &v
}

// GetExpiryDate returns the ExpiryDate field value if set, zero value otherwise.
func (o *NewCouponsForMultipleRecipients) GetExpiryDate() time.Time {
	if o == nil || o.ExpiryDate == nil {
		var ret time.Time
		return ret
	}
	return *o.ExpiryDate
}

// GetExpiryDateOk returns a tuple with the ExpiryDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewCouponsForMultipleRecipients) GetExpiryDateOk() (*time.Time, bool) {
	if o == nil || o.ExpiryDate == nil {
		return nil, false
	}
	return o.ExpiryDate, true
}

// HasExpiryDate returns a boolean if a field has been set.
func (o *NewCouponsForMultipleRecipients) HasExpiryDate() bool {
	if o != nil && o.ExpiryDate != nil {
		return true
	}

	return false
}

// SetExpiryDate gets a reference to the given time.Time and assigns it to the ExpiryDate field.
func (o *NewCouponsForMultipleRecipients) SetExpiryDate(v time.Time) {
	o.ExpiryDate = &v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *NewCouponsForMultipleRecipients) GetAttributes() map[string]interface{} {
	if o == nil || o.Attributes == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewCouponsForMultipleRecipients) GetAttributesOk() (map[string]interface{}, bool) {
	if o == nil || o.Attributes == nil {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *NewCouponsForMultipleRecipients) HasAttributes() bool {
	if o != nil && o.Attributes != nil {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given map[string]interface{} and assigns it to the Attributes field.
func (o *NewCouponsForMultipleRecipients) SetAttributes(v map[string]interface{}) {
	o.Attributes = v
}

// GetRecipientsIntegrationIds returns the RecipientsIntegrationIds field value
func (o *NewCouponsForMultipleRecipients) GetRecipientsIntegrationIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.RecipientsIntegrationIds
}

// GetRecipientsIntegrationIdsOk returns a tuple with the RecipientsIntegrationIds field value
// and a boolean to check if the value has been set.
func (o *NewCouponsForMultipleRecipients) GetRecipientsIntegrationIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RecipientsIntegrationIds, true
}

// SetRecipientsIntegrationIds sets field value
func (o *NewCouponsForMultipleRecipients) SetRecipientsIntegrationIds(v []string) {
	o.RecipientsIntegrationIds = v
}

// GetValidCharacters returns the ValidCharacters field value if set, zero value otherwise.
func (o *NewCouponsForMultipleRecipients) GetValidCharacters() []string {
	if o == nil || o.ValidCharacters == nil {
		var ret []string
		return ret
	}
	return o.ValidCharacters
}

// GetValidCharactersOk returns a tuple with the ValidCharacters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewCouponsForMultipleRecipients) GetValidCharactersOk() ([]string, bool) {
	if o == nil || o.ValidCharacters == nil {
		return nil, false
	}
	return o.ValidCharacters, true
}

// HasValidCharacters returns a boolean if a field has been set.
func (o *NewCouponsForMultipleRecipients) HasValidCharacters() bool {
	if o != nil && o.ValidCharacters != nil {
		return true
	}

	return false
}

// SetValidCharacters gets a reference to the given []string and assigns it to the ValidCharacters field.
func (o *NewCouponsForMultipleRecipients) SetValidCharacters(v []string) {
	o.ValidCharacters = v
}

// GetCouponPattern returns the CouponPattern field value if set, zero value otherwise.
func (o *NewCouponsForMultipleRecipients) GetCouponPattern() string {
	if o == nil || o.CouponPattern == nil {
		var ret string
		return ret
	}
	return *o.CouponPattern
}

// GetCouponPatternOk returns a tuple with the CouponPattern field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewCouponsForMultipleRecipients) GetCouponPatternOk() (*string, bool) {
	if o == nil || o.CouponPattern == nil {
		return nil, false
	}
	return o.CouponPattern, true
}

// HasCouponPattern returns a boolean if a field has been set.
func (o *NewCouponsForMultipleRecipients) HasCouponPattern() bool {
	if o != nil && o.CouponPattern != nil {
		return true
	}

	return false
}

// SetCouponPattern gets a reference to the given string and assigns it to the CouponPattern field.
func (o *NewCouponsForMultipleRecipients) SetCouponPattern(v string) {
	o.CouponPattern = &v
}

func (o NewCouponsForMultipleRecipients) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["usageLimit"] = o.UsageLimit
	}
	if o.DiscountLimit != nil {
		toSerialize["discountLimit"] = o.DiscountLimit
	}
	if o.StartDate != nil {
		toSerialize["startDate"] = o.StartDate
	}
	if o.ExpiryDate != nil {
		toSerialize["expiryDate"] = o.ExpiryDate
	}
	if o.Attributes != nil {
		toSerialize["attributes"] = o.Attributes
	}
	if true {
		toSerialize["recipientsIntegrationIds"] = o.RecipientsIntegrationIds
	}
	if o.ValidCharacters != nil {
		toSerialize["validCharacters"] = o.ValidCharacters
	}
	if o.CouponPattern != nil {
		toSerialize["couponPattern"] = o.CouponPattern
	}
	return json.Marshal(toSerialize)
}

type NullableNewCouponsForMultipleRecipients struct {
	value *NewCouponsForMultipleRecipients
	isSet bool
}

func (v NullableNewCouponsForMultipleRecipients) Get() *NewCouponsForMultipleRecipients {
	return v.value
}

func (v *NullableNewCouponsForMultipleRecipients) Set(val *NewCouponsForMultipleRecipients) {
	v.value = val
	v.isSet = true
}

func (v NullableNewCouponsForMultipleRecipients) IsSet() bool {
	return v.isSet
}

func (v *NullableNewCouponsForMultipleRecipients) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNewCouponsForMultipleRecipients(val *NewCouponsForMultipleRecipients) *NullableNewCouponsForMultipleRecipients {
	return &NullableNewCouponsForMultipleRecipients{value: val, isSet: true}
}

func (v NullableNewCouponsForMultipleRecipients) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNewCouponsForMultipleRecipients) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


