/*
Integration API reference docs

Use the Integration API to push data to and retrieve data from Talon.One in real time. For more background information about this API, see [Integration API overview](/docs/dev/integration-api/overview)  For example, use this API to share shopping cart information as a session with Talon.One and evaluate promotion rules. You can also create custom events to track specific actions that do not fit into the session data model.  Ensure you [authenticate](#section/Authentication) to make requests to the API.  <div class=\"redoc-section\">   <p class=\"title\">Are you looking for a different API?</p>    If you need the API to:    - Interact with the Campaign Manager for backoffice operations, see [the Management API reference docs](https://docs.talon.one/management-api).   - Integrate with Talon.One from a CEP or CDP platform, see [the Third-party API reference docs](https://docs.talon.one/third-party-api).  </div>  # Authentication  <SecurityDefinitions /> 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
)

// CampaignNotification struct for CampaignNotification
type CampaignNotification struct {
	// The type of the event. Can be one of the following: ['campaign_state_changed', 'campaign_ruleset_changed', 'campaign_edited', 'campaign_created', 'campaign_deleted'] 
	Event string `json:"event"`
}

// NewCampaignNotification instantiates a new CampaignNotification object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCampaignNotification(event string) *CampaignNotification {
	this := CampaignNotification{}
	this.Event = event
	return &this
}

// NewCampaignNotificationWithDefaults instantiates a new CampaignNotification object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCampaignNotificationWithDefaults() *CampaignNotification {
	this := CampaignNotification{}
	return &this
}

// GetEvent returns the Event field value
func (o *CampaignNotification) GetEvent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Event
}

// GetEventOk returns a tuple with the Event field value
// and a boolean to check if the value has been set.
func (o *CampaignNotification) GetEventOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Event, true
}

// SetEvent sets field value
func (o *CampaignNotification) SetEvent(v string) {
	o.Event = v
}

func (o CampaignNotification) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["event"] = o.Event
	}
	return json.Marshal(toSerialize)
}

type NullableCampaignNotification struct {
	value *CampaignNotification
	isSet bool
}

func (v NullableCampaignNotification) Get() *CampaignNotification {
	return v.value
}

func (v *NullableCampaignNotification) Set(val *CampaignNotification) {
	v.value = val
	v.isSet = true
}

func (v NullableCampaignNotification) IsSet() bool {
	return v.isSet
}

func (v *NullableCampaignNotification) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCampaignNotification(val *CampaignNotification) *NullableCampaignNotification {
	return &NullableCampaignNotification{value: val, isSet: true}
}

func (v NullableCampaignNotification) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCampaignNotification) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


