/*
Integration API reference docs

Use the Integration API to push data to and retrieve data from Talon.One in real time. For more background information about this API, see [Integration API overview](/docs/dev/integration-api/overview)  For example, use this API to share shopping cart information as a session with Talon.One and evaluate promotion rules. You can also create custom events to track specific actions that do not fit into the session data model.  Ensure you [authenticate](#section/Authentication) to make requests to the API.  <div class=\"redoc-section\">   <p class=\"title\">Are you looking for a different API?</p>    If you need the API to:    - Interact with the Campaign Manager for backoffice operations, see [the Management API reference docs](https://docs.talon.one/management-api).   - Integrate with Talon.One from a CEP or CDP platform, see [the Third-party API reference docs](https://docs.talon.one/third-party-api).  </div>  # Authentication  <SecurityDefinitions /> 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
)

// CustomerProfileAudienceRequest struct for CustomerProfileAudienceRequest
type CustomerProfileAudienceRequest struct {
	Data []CustomerProfileAudienceRequestItem `json:"data,omitempty"`
}

// NewCustomerProfileAudienceRequest instantiates a new CustomerProfileAudienceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerProfileAudienceRequest() *CustomerProfileAudienceRequest {
	this := CustomerProfileAudienceRequest{}
	return &this
}

// NewCustomerProfileAudienceRequestWithDefaults instantiates a new CustomerProfileAudienceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerProfileAudienceRequestWithDefaults() *CustomerProfileAudienceRequest {
	this := CustomerProfileAudienceRequest{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CustomerProfileAudienceRequest) GetData() []CustomerProfileAudienceRequestItem {
	if o == nil || o.Data == nil {
		var ret []CustomerProfileAudienceRequestItem
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerProfileAudienceRequest) GetDataOk() ([]CustomerProfileAudienceRequestItem, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CustomerProfileAudienceRequest) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given []CustomerProfileAudienceRequestItem and assigns it to the Data field.
func (o *CustomerProfileAudienceRequest) SetData(v []CustomerProfileAudienceRequestItem) {
	o.Data = v
}

func (o CustomerProfileAudienceRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableCustomerProfileAudienceRequest struct {
	value *CustomerProfileAudienceRequest
	isSet bool
}

func (v NullableCustomerProfileAudienceRequest) Get() *CustomerProfileAudienceRequest {
	return v.value
}

func (v *NullableCustomerProfileAudienceRequest) Set(val *CustomerProfileAudienceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerProfileAudienceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerProfileAudienceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerProfileAudienceRequest(val *CustomerProfileAudienceRequest) *NullableCustomerProfileAudienceRequest {
	return &NullableCustomerProfileAudienceRequest{value: val, isSet: true}
}

func (v NullableCustomerProfileAudienceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerProfileAudienceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


