/*
Integration API reference docs

Use the Integration API to push data to and retrieve data from Talon.One in real time. For more background information about this API, see [Integration API overview](/docs/dev/integration-api/overview)  For example, use this API to share shopping cart information as a session with Talon.One and evaluate promotion rules. You can also create custom events to track specific actions that do not fit into the session data model.  Ensure you [authenticate](#section/Authentication) to make requests to the API.  <div class=\"redoc-section\">   <p class=\"title\">Are you looking for a different API?</p>    If you need the API to:    - Interact with the Campaign Manager for backoffice operations, see [the Management API reference docs](https://docs.talon.one/management-api).   - Integrate with Talon.One from a CEP or CDP platform, see [the Third-party API reference docs](https://docs.talon.one/third-party-api).  </div>  # Authentication  <SecurityDefinitions /> 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
)

// IntegrationRequest The body of a V2 integration API request (customer session update). Next to the customer session details, this contains an optional listing of extra properties that should be returned in the response.
type IntegrationRequest struct {
	CustomerSession NewCustomerSessionV2 `json:"customerSession"`
	// Optional list of extra data that you want to get in the response. Use this property to get as much data as you need in one request instead of sending extra requests to other endpoints.  **Note:** `ruleFailureReasons` is always part of the response when the [Application type](https://docs.talon.one/docs/product/applications/overview#application-types) is `sandbox`. 
	ResponseContent []string `json:"responseContent,omitempty"`
}

// NewIntegrationRequest instantiates a new IntegrationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntegrationRequest(customerSession NewCustomerSessionV2) *IntegrationRequest {
	this := IntegrationRequest{}
	this.CustomerSession = customerSession
	return &this
}

// NewIntegrationRequestWithDefaults instantiates a new IntegrationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntegrationRequestWithDefaults() *IntegrationRequest {
	this := IntegrationRequest{}
	return &this
}

// GetCustomerSession returns the CustomerSession field value
func (o *IntegrationRequest) GetCustomerSession() NewCustomerSessionV2 {
	if o == nil {
		var ret NewCustomerSessionV2
		return ret
	}

	return o.CustomerSession
}

// GetCustomerSessionOk returns a tuple with the CustomerSession field value
// and a boolean to check if the value has been set.
func (o *IntegrationRequest) GetCustomerSessionOk() (*NewCustomerSessionV2, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomerSession, true
}

// SetCustomerSession sets field value
func (o *IntegrationRequest) SetCustomerSession(v NewCustomerSessionV2) {
	o.CustomerSession = v
}

// GetResponseContent returns the ResponseContent field value if set, zero value otherwise.
func (o *IntegrationRequest) GetResponseContent() []string {
	if o == nil || o.ResponseContent == nil {
		var ret []string
		return ret
	}
	return o.ResponseContent
}

// GetResponseContentOk returns a tuple with the ResponseContent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntegrationRequest) GetResponseContentOk() ([]string, bool) {
	if o == nil || o.ResponseContent == nil {
		return nil, false
	}
	return o.ResponseContent, true
}

// HasResponseContent returns a boolean if a field has been set.
func (o *IntegrationRequest) HasResponseContent() bool {
	if o != nil && o.ResponseContent != nil {
		return true
	}

	return false
}

// SetResponseContent gets a reference to the given []string and assigns it to the ResponseContent field.
func (o *IntegrationRequest) SetResponseContent(v []string) {
	o.ResponseContent = v
}

func (o IntegrationRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["customerSession"] = o.CustomerSession
	}
	if o.ResponseContent != nil {
		toSerialize["responseContent"] = o.ResponseContent
	}
	return json.Marshal(toSerialize)
}

type NullableIntegrationRequest struct {
	value *IntegrationRequest
	isSet bool
}

func (v NullableIntegrationRequest) Get() *IntegrationRequest {
	return v.value
}

func (v *NullableIntegrationRequest) Set(val *IntegrationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableIntegrationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableIntegrationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntegrationRequest(val *IntegrationRequest) *NullableIntegrationRequest {
	return &NullableIntegrationRequest{value: val, isSet: true}
}

func (v NullableIntegrationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntegrationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


