/*
Integration API reference docs

Use the Integration API to push data to and retrieve data from Talon.One in real time. For more background information about this API, see [Integration API overview](/docs/dev/integration-api/overview)  For example, use this API to share shopping cart information as a session with Talon.One and evaluate promotion rules. You can also create custom events to track specific actions that do not fit into the session data model.  Ensure you [authenticate](#section/Authentication) to make requests to the API.  <div class=\"redoc-section\">   <p class=\"title\">Are you looking for a different API?</p>    If you need the API to:    - Interact with the Campaign Manager for backoffice operations, see [the Management API reference docs](https://docs.talon.one/management-api).   - Integrate with Talon.One from a CEP or CDP platform, see [the Third-party API reference docs](https://docs.talon.one/third-party-api).  </div>  # Authentication  <SecurityDefinitions /> 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
)

// NewAccountSignUp 
type NewAccountSignUp struct {
	// The email address associated with your account.
	Email string `json:"email"`
	// The password for your account.
	Password string `json:"password"`
	CompanyName string `json:"companyName"`
}

// NewNewAccountSignUp instantiates a new NewAccountSignUp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNewAccountSignUp(email string, password string, companyName string) *NewAccountSignUp {
	this := NewAccountSignUp{}
	this.Email = email
	this.Password = password
	this.CompanyName = companyName
	return &this
}

// NewNewAccountSignUpWithDefaults instantiates a new NewAccountSignUp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNewAccountSignUpWithDefaults() *NewAccountSignUp {
	this := NewAccountSignUp{}
	return &this
}

// GetEmail returns the Email field value
func (o *NewAccountSignUp) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *NewAccountSignUp) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *NewAccountSignUp) SetEmail(v string) {
	o.Email = v
}

// GetPassword returns the Password field value
func (o *NewAccountSignUp) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *NewAccountSignUp) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *NewAccountSignUp) SetPassword(v string) {
	o.Password = v
}

// GetCompanyName returns the CompanyName field value
func (o *NewAccountSignUp) GetCompanyName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CompanyName
}

// GetCompanyNameOk returns a tuple with the CompanyName field value
// and a boolean to check if the value has been set.
func (o *NewAccountSignUp) GetCompanyNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CompanyName, true
}

// SetCompanyName sets field value
func (o *NewAccountSignUp) SetCompanyName(v string) {
	o.CompanyName = v
}

func (o NewAccountSignUp) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["email"] = o.Email
	}
	if true {
		toSerialize["password"] = o.Password
	}
	if true {
		toSerialize["companyName"] = o.CompanyName
	}
	return json.Marshal(toSerialize)
}

type NullableNewAccountSignUp struct {
	value *NewAccountSignUp
	isSet bool
}

func (v NullableNewAccountSignUp) Get() *NewAccountSignUp {
	return v.value
}

func (v *NullableNewAccountSignUp) Set(val *NewAccountSignUp) {
	v.value = val
	v.isSet = true
}

func (v NullableNewAccountSignUp) IsSet() bool {
	return v.isSet
}

func (v *NullableNewAccountSignUp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNewAccountSignUp(val *NewAccountSignUp) *NullableNewAccountSignUp {
	return &NullableNewAccountSignUp{value: val, isSet: true}
}

func (v NullableNewAccountSignUp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNewAccountSignUp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


