/*
Integration API reference docs

Use the Integration API to push data to and retrieve data from Talon.One in real time. For more background information about this API, see [Integration API overview](/docs/dev/integration-api/overview)  For example, use this API to share shopping cart information as a session with Talon.One and evaluate promotion rules. You can also create custom events to track specific actions that do not fit into the session data model.  Ensure you [authenticate](#section/Authentication) to make requests to the API.  <div class=\"redoc-section\">   <p class=\"title\">Are you looking for a different API?</p>    If you need the API to:    - Interact with the Campaign Manager for backoffice operations, see [the Management API reference docs](https://docs.talon.one/management-api).   - Integrate with Talon.One from a CEP or CDP platform, see [the Third-party API reference docs](https://docs.talon.one/third-party-api).  </div>  # Authentication  <SecurityDefinitions /> 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
)

// MultiApplicationEntity struct for MultiApplicationEntity
type MultiApplicationEntity struct {
	// The IDs of the applications that are related to this entity.
	ApplicationIds []int32 `json:"applicationIds"`
}

// NewMultiApplicationEntity instantiates a new MultiApplicationEntity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMultiApplicationEntity(applicationIds []int32) *MultiApplicationEntity {
	this := MultiApplicationEntity{}
	this.ApplicationIds = applicationIds
	return &this
}

// NewMultiApplicationEntityWithDefaults instantiates a new MultiApplicationEntity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMultiApplicationEntityWithDefaults() *MultiApplicationEntity {
	this := MultiApplicationEntity{}
	return &this
}

// GetApplicationIds returns the ApplicationIds field value
func (o *MultiApplicationEntity) GetApplicationIds() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}

	return o.ApplicationIds
}

// GetApplicationIdsOk returns a tuple with the ApplicationIds field value
// and a boolean to check if the value has been set.
func (o *MultiApplicationEntity) GetApplicationIdsOk() ([]int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ApplicationIds, true
}

// SetApplicationIds sets field value
func (o *MultiApplicationEntity) SetApplicationIds(v []int32) {
	o.ApplicationIds = v
}

func (o MultiApplicationEntity) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["applicationIds"] = o.ApplicationIds
	}
	return json.Marshal(toSerialize)
}

type NullableMultiApplicationEntity struct {
	value *MultiApplicationEntity
	isSet bool
}

func (v NullableMultiApplicationEntity) Get() *MultiApplicationEntity {
	return v.value
}

func (v *NullableMultiApplicationEntity) Set(val *MultiApplicationEntity) {
	v.value = val
	v.isSet = true
}

func (v NullableMultiApplicationEntity) IsSet() bool {
	return v.isSet
}

func (v *NullableMultiApplicationEntity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMultiApplicationEntity(val *MultiApplicationEntity) *NullableMultiApplicationEntity {
	return &NullableMultiApplicationEntity{value: val, isSet: true}
}

func (v NullableMultiApplicationEntity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMultiApplicationEntity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


