/*
Integration API reference docs

Use the Integration API to push data to and retrieve data from Talon.One in real time. For more background information about this API, see [Integration API overview](/docs/dev/integration-api/overview)  For example, use this API to share shopping cart information as a session with Talon.One and evaluate promotion rules. You can also create custom events to track specific actions that do not fit into the session data model.  Ensure you [authenticate](#section/Authentication) to make requests to the API.  <div class=\"redoc-section\">   <p class=\"title\">Are you looking for a different API?</p>    If you need the API to:    - Interact with the Campaign Manager for backoffice operations, see [the Management API reference docs](https://docs.talon.one/management-api).   - Integrate with Talon.One from a CEP or CDP platform, see [the Third-party API reference docs](https://docs.talon.one/third-party-api).  </div>  # Authentication  <SecurityDefinitions /> 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
)

// RollbackAddedLoyaltyPointsEffectProps The properties specific to the \"rollbackAddedLoyaltyPoints\" effect. This gets triggered whenever previously a closed session with an addLoyaltyPoints effect is cancelled.
type RollbackAddedLoyaltyPointsEffectProps struct {
	// The ID of the loyalty program where the points were originally added.
	ProgramId int32 `json:"programId"`
	// The ID of the subledger within the loyalty program where these points were originally added.
	SubLedgerId string `json:"subLedgerId"`
	// The amount of points that were rolled back.
	Value float32 `json:"value"`
	// The user for whom these points were originally added.
	RecipientIntegrationId string `json:"recipientIntegrationId"`
	// The identifier of 'deduction' entry added to the ledger as the `addLoyaltyPoints` effect is rolled back.
	TransactionUUID string `json:"transactionUUID"`
	// The index of the item in the cart items for which the loyalty points were rolled back.
	CartItemPosition *float32 `json:"cartItemPosition,omitempty"`
	// The sub-position is returned when [cart item flattening](https://docs.talon.one/docs/product/campaigns/campaign-evaluation/#flattened-cart-items) is enabled. It indicates to which item the loyalty points were rolled back, for cart items with `quantity` > 1. 
	CartItemSubPosition *float32 `json:"cartItemSubPosition,omitempty"`
	// The card on which these points were originally added.
	CardIdentifier *string `json:"cardIdentifier,omitempty"`
}

// NewRollbackAddedLoyaltyPointsEffectProps instantiates a new RollbackAddedLoyaltyPointsEffectProps object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRollbackAddedLoyaltyPointsEffectProps(programId int32, subLedgerId string, value float32, recipientIntegrationId string, transactionUUID string) *RollbackAddedLoyaltyPointsEffectProps {
	this := RollbackAddedLoyaltyPointsEffectProps{}
	this.ProgramId = programId
	this.SubLedgerId = subLedgerId
	this.Value = value
	this.RecipientIntegrationId = recipientIntegrationId
	this.TransactionUUID = transactionUUID
	return &this
}

// NewRollbackAddedLoyaltyPointsEffectPropsWithDefaults instantiates a new RollbackAddedLoyaltyPointsEffectProps object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRollbackAddedLoyaltyPointsEffectPropsWithDefaults() *RollbackAddedLoyaltyPointsEffectProps {
	this := RollbackAddedLoyaltyPointsEffectProps{}
	return &this
}

// GetProgramId returns the ProgramId field value
func (o *RollbackAddedLoyaltyPointsEffectProps) GetProgramId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ProgramId
}

// GetProgramIdOk returns a tuple with the ProgramId field value
// and a boolean to check if the value has been set.
func (o *RollbackAddedLoyaltyPointsEffectProps) GetProgramIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProgramId, true
}

// SetProgramId sets field value
func (o *RollbackAddedLoyaltyPointsEffectProps) SetProgramId(v int32) {
	o.ProgramId = v
}

// GetSubLedgerId returns the SubLedgerId field value
func (o *RollbackAddedLoyaltyPointsEffectProps) GetSubLedgerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SubLedgerId
}

// GetSubLedgerIdOk returns a tuple with the SubLedgerId field value
// and a boolean to check if the value has been set.
func (o *RollbackAddedLoyaltyPointsEffectProps) GetSubLedgerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubLedgerId, true
}

// SetSubLedgerId sets field value
func (o *RollbackAddedLoyaltyPointsEffectProps) SetSubLedgerId(v string) {
	o.SubLedgerId = v
}

// GetValue returns the Value field value
func (o *RollbackAddedLoyaltyPointsEffectProps) GetValue() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *RollbackAddedLoyaltyPointsEffectProps) GetValueOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *RollbackAddedLoyaltyPointsEffectProps) SetValue(v float32) {
	o.Value = v
}

// GetRecipientIntegrationId returns the RecipientIntegrationId field value
func (o *RollbackAddedLoyaltyPointsEffectProps) GetRecipientIntegrationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RecipientIntegrationId
}

// GetRecipientIntegrationIdOk returns a tuple with the RecipientIntegrationId field value
// and a boolean to check if the value has been set.
func (o *RollbackAddedLoyaltyPointsEffectProps) GetRecipientIntegrationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RecipientIntegrationId, true
}

// SetRecipientIntegrationId sets field value
func (o *RollbackAddedLoyaltyPointsEffectProps) SetRecipientIntegrationId(v string) {
	o.RecipientIntegrationId = v
}

// GetTransactionUUID returns the TransactionUUID field value
func (o *RollbackAddedLoyaltyPointsEffectProps) GetTransactionUUID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransactionUUID
}

// GetTransactionUUIDOk returns a tuple with the TransactionUUID field value
// and a boolean to check if the value has been set.
func (o *RollbackAddedLoyaltyPointsEffectProps) GetTransactionUUIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransactionUUID, true
}

// SetTransactionUUID sets field value
func (o *RollbackAddedLoyaltyPointsEffectProps) SetTransactionUUID(v string) {
	o.TransactionUUID = v
}

// GetCartItemPosition returns the CartItemPosition field value if set, zero value otherwise.
func (o *RollbackAddedLoyaltyPointsEffectProps) GetCartItemPosition() float32 {
	if o == nil || o.CartItemPosition == nil {
		var ret float32
		return ret
	}
	return *o.CartItemPosition
}

// GetCartItemPositionOk returns a tuple with the CartItemPosition field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RollbackAddedLoyaltyPointsEffectProps) GetCartItemPositionOk() (*float32, bool) {
	if o == nil || o.CartItemPosition == nil {
		return nil, false
	}
	return o.CartItemPosition, true
}

// HasCartItemPosition returns a boolean if a field has been set.
func (o *RollbackAddedLoyaltyPointsEffectProps) HasCartItemPosition() bool {
	if o != nil && o.CartItemPosition != nil {
		return true
	}

	return false
}

// SetCartItemPosition gets a reference to the given float32 and assigns it to the CartItemPosition field.
func (o *RollbackAddedLoyaltyPointsEffectProps) SetCartItemPosition(v float32) {
	o.CartItemPosition = &v
}

// GetCartItemSubPosition returns the CartItemSubPosition field value if set, zero value otherwise.
func (o *RollbackAddedLoyaltyPointsEffectProps) GetCartItemSubPosition() float32 {
	if o == nil || o.CartItemSubPosition == nil {
		var ret float32
		return ret
	}
	return *o.CartItemSubPosition
}

// GetCartItemSubPositionOk returns a tuple with the CartItemSubPosition field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RollbackAddedLoyaltyPointsEffectProps) GetCartItemSubPositionOk() (*float32, bool) {
	if o == nil || o.CartItemSubPosition == nil {
		return nil, false
	}
	return o.CartItemSubPosition, true
}

// HasCartItemSubPosition returns a boolean if a field has been set.
func (o *RollbackAddedLoyaltyPointsEffectProps) HasCartItemSubPosition() bool {
	if o != nil && o.CartItemSubPosition != nil {
		return true
	}

	return false
}

// SetCartItemSubPosition gets a reference to the given float32 and assigns it to the CartItemSubPosition field.
func (o *RollbackAddedLoyaltyPointsEffectProps) SetCartItemSubPosition(v float32) {
	o.CartItemSubPosition = &v
}

// GetCardIdentifier returns the CardIdentifier field value if set, zero value otherwise.
func (o *RollbackAddedLoyaltyPointsEffectProps) GetCardIdentifier() string {
	if o == nil || o.CardIdentifier == nil {
		var ret string
		return ret
	}
	return *o.CardIdentifier
}

// GetCardIdentifierOk returns a tuple with the CardIdentifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RollbackAddedLoyaltyPointsEffectProps) GetCardIdentifierOk() (*string, bool) {
	if o == nil || o.CardIdentifier == nil {
		return nil, false
	}
	return o.CardIdentifier, true
}

// HasCardIdentifier returns a boolean if a field has been set.
func (o *RollbackAddedLoyaltyPointsEffectProps) HasCardIdentifier() bool {
	if o != nil && o.CardIdentifier != nil {
		return true
	}

	return false
}

// SetCardIdentifier gets a reference to the given string and assigns it to the CardIdentifier field.
func (o *RollbackAddedLoyaltyPointsEffectProps) SetCardIdentifier(v string) {
	o.CardIdentifier = &v
}

func (o RollbackAddedLoyaltyPointsEffectProps) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["programId"] = o.ProgramId
	}
	if true {
		toSerialize["subLedgerId"] = o.SubLedgerId
	}
	if true {
		toSerialize["value"] = o.Value
	}
	if true {
		toSerialize["recipientIntegrationId"] = o.RecipientIntegrationId
	}
	if true {
		toSerialize["transactionUUID"] = o.TransactionUUID
	}
	if o.CartItemPosition != nil {
		toSerialize["cartItemPosition"] = o.CartItemPosition
	}
	if o.CartItemSubPosition != nil {
		toSerialize["cartItemSubPosition"] = o.CartItemSubPosition
	}
	if o.CardIdentifier != nil {
		toSerialize["cardIdentifier"] = o.CardIdentifier
	}
	return json.Marshal(toSerialize)
}

type NullableRollbackAddedLoyaltyPointsEffectProps struct {
	value *RollbackAddedLoyaltyPointsEffectProps
	isSet bool
}

func (v NullableRollbackAddedLoyaltyPointsEffectProps) Get() *RollbackAddedLoyaltyPointsEffectProps {
	return v.value
}

func (v *NullableRollbackAddedLoyaltyPointsEffectProps) Set(val *RollbackAddedLoyaltyPointsEffectProps) {
	v.value = val
	v.isSet = true
}

func (v NullableRollbackAddedLoyaltyPointsEffectProps) IsSet() bool {
	return v.isSet
}

func (v *NullableRollbackAddedLoyaltyPointsEffectProps) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRollbackAddedLoyaltyPointsEffectProps(val *RollbackAddedLoyaltyPointsEffectProps) *NullableRollbackAddedLoyaltyPointsEffectProps {
	return &NullableRollbackAddedLoyaltyPointsEffectProps{value: val, isSet: true}
}

func (v NullableRollbackAddedLoyaltyPointsEffectProps) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRollbackAddedLoyaltyPointsEffectProps) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


