/*
Integration API reference docs

Use the Integration API to push data to and retrieve data from Talon.One in real time. For more background information about this API, see [Integration API overview](/docs/dev/integration-api/overview)  For example, use this API to share shopping cart information as a session with Talon.One and evaluate promotion rules. You can also create custom events to track specific actions that do not fit into the session data model.  Ensure you [authenticate](#section/Authentication) to make requests to the API.  <div class=\"redoc-section\">   <p class=\"title\">Are you looking for a different API?</p>    If you need the API to:    - Interact with the Campaign Manager for backoffice operations, see [the Management API reference docs](https://docs.talon.one/management-api).   - Integrate with Talon.One from a CEP or CDP platform, see [the Third-party API reference docs](https://docs.talon.one/third-party-api).  </div>  # Authentication  <SecurityDefinitions /> 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
	"time"
)

// Campaign 
type Campaign struct {
	// Unique ID for this entity.
	Id int32 `json:"id"`
	// The exact moment this entity was created.
	Created time.Time `json:"created"`
	// The ID of the application that owns this entity.
	ApplicationId int32 `json:"applicationId"`
	// The ID of the account that owns this entity.
	UserId int32 `json:"userId"`
	// A user-facing name for this campaign.
	Name string `json:"name"`
	// A detailed description of the campaign.
	Description string `json:"description"`
	// Timestamp when the campaign will become active.
	StartTime *time.Time `json:"startTime,omitempty"`
	// Timestamp the campaign will become inactive.
	EndTime *time.Time `json:"endTime,omitempty"`
	// Arbitrary properties associated with this campaign.
	Attributes map[string]interface{} `json:"attributes,omitempty"`
	// A disabled or archived campaign is not evaluated for rules or coupons. 
	State string `json:"state"`
	// [ID of Ruleset](https://docs.talon.one/management-api/#operation/getRulesets) this campaign applies on customer session evaluation. 
	ActiveRulesetId *int32 `json:"activeRulesetId,omitempty"`
	// A list of tags for the campaign.
	Tags []string `json:"tags"`
	// The features enabled in this campaign.
	Features []string `json:"features"`
	CouponSettings *CodeGeneratorSettings `json:"couponSettings,omitempty"`
	ReferralSettings *CodeGeneratorSettings `json:"referralSettings,omitempty"`
	// The set of [budget limits](https://docs.talon.one/docs/product/campaigns/settings/managing-campaign-budgets/) for this campaign. 
	Limits []LimitConfig `json:"limits"`
	// The IDs of the [campaign groups](https://docs.talon.one/docs/product/account/managing-campaign-groups/) this campaign belongs to. 
	CampaignGroups []int32 `json:"campaignGroups,omitempty"`
	// Number of coupons redeemed in the campaign.
	CouponRedemptionCount *int32 `json:"couponRedemptionCount,omitempty"`
	// Number of referral codes redeemed in the campaign.
	ReferralRedemptionCount *int32 `json:"referralRedemptionCount,omitempty"`
	// Total amount of discounts redeemed in the campaign.
	DiscountCount *float32 `json:"discountCount,omitempty"`
	// Total number of times discounts were redeemed in this campaign.
	DiscountEffectCount *int32 `json:"discountEffectCount,omitempty"`
	// Total number of coupons created by rules in this campaign.
	CouponCreationCount *int32 `json:"couponCreationCount,omitempty"`
	// Total number of custom effects triggered by rules in this campaign.
	CustomEffectCount *int32 `json:"customEffectCount,omitempty"`
	// Total number of referrals created by rules in this campaign.
	ReferralCreationCount *int32 `json:"referralCreationCount,omitempty"`
	// Total number of times triggering add free item effext is allowed in this campaign.
	AddFreeItemEffectCount *int32 `json:"addFreeItemEffectCount,omitempty"`
	// Total number of giveaways awarded by rules in this campaign.
	AwardedGiveawaysCount *int32 `json:"awardedGiveawaysCount,omitempty"`
	// Total number of loyalty points created by rules in this campaign.
	CreatedLoyaltyPointsCount *float32 `json:"createdLoyaltyPointsCount,omitempty"`
	// Total number of loyalty point creation effects triggered by rules in this campaign.
	CreatedLoyaltyPointsEffectCount *int32 `json:"createdLoyaltyPointsEffectCount,omitempty"`
	// Total number of loyalty points redeemed by rules in this campaign.
	RedeemedLoyaltyPointsCount *float32 `json:"redeemedLoyaltyPointsCount,omitempty"`
	// Total number of loyalty point redemption effects triggered by rules in this campaign.
	RedeemedLoyaltyPointsEffectCount *int32 `json:"redeemedLoyaltyPointsEffectCount,omitempty"`
	// Total number of webhook triggered by rules in this campaign.
	CallApiEffectCount *int32 `json:"callApiEffectCount,omitempty"`
	// Timestamp of the most recent event received by this campaign.
	LastActivity *time.Time `json:"lastActivity,omitempty"`
	// Timestamp of the most recent update to the campaign's property. Updates to external entities used in this campaign are **not** registered by this property, such as collection or coupon updates. 
	Updated *time.Time `json:"updated,omitempty"`
	// Name of the user who created this campaign if available.
	CreatedBy *string `json:"createdBy,omitempty"`
	// Name of the user who last updated this campaign if available.
	UpdatedBy *string `json:"updatedBy,omitempty"`
	// The ID of the Campaign Template this Campaign was created from.
	TemplateId *int32 `json:"templateId,omitempty"`
}

// NewCampaign instantiates a new Campaign object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCampaign(id int32, created time.Time, applicationId int32, userId int32, name string, description string, state string, tags []string, features []string, limits []LimitConfig) *Campaign {
	this := Campaign{}
	this.Id = id
	this.Created = created
	this.ApplicationId = applicationId
	this.UserId = userId
	this.Name = name
	this.Description = description
	this.State = state
	this.Tags = tags
	this.Features = features
	this.Limits = limits
	return &this
}

// NewCampaignWithDefaults instantiates a new Campaign object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCampaignWithDefaults() *Campaign {
	this := Campaign{}
	var state string = "enabled"
	this.State = state
	return &this
}

// GetId returns the Id field value
func (o *Campaign) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Campaign) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Campaign) SetId(v int32) {
	o.Id = v
}

// GetCreated returns the Created field value
func (o *Campaign) GetCreated() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *Campaign) GetCreatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *Campaign) SetCreated(v time.Time) {
	o.Created = v
}

// GetApplicationId returns the ApplicationId field value
func (o *Campaign) GetApplicationId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ApplicationId
}

// GetApplicationIdOk returns a tuple with the ApplicationId field value
// and a boolean to check if the value has been set.
func (o *Campaign) GetApplicationIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApplicationId, true
}

// SetApplicationId sets field value
func (o *Campaign) SetApplicationId(v int32) {
	o.ApplicationId = v
}

// GetUserId returns the UserId field value
func (o *Campaign) GetUserId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *Campaign) GetUserIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *Campaign) SetUserId(v int32) {
	o.UserId = v
}

// GetName returns the Name field value
func (o *Campaign) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Campaign) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Campaign) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *Campaign) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *Campaign) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *Campaign) SetDescription(v string) {
	o.Description = v
}

// GetStartTime returns the StartTime field value if set, zero value otherwise.
func (o *Campaign) GetStartTime() time.Time {
	if o == nil || o.StartTime == nil {
		var ret time.Time
		return ret
	}
	return *o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Campaign) GetStartTimeOk() (*time.Time, bool) {
	if o == nil || o.StartTime == nil {
		return nil, false
	}
	return o.StartTime, true
}

// HasStartTime returns a boolean if a field has been set.
func (o *Campaign) HasStartTime() bool {
	if o != nil && o.StartTime != nil {
		return true
	}

	return false
}

// SetStartTime gets a reference to the given time.Time and assigns it to the StartTime field.
func (o *Campaign) SetStartTime(v time.Time) {
	o.StartTime = &v
}

// GetEndTime returns the EndTime field value if set, zero value otherwise.
func (o *Campaign) GetEndTime() time.Time {
	if o == nil || o.EndTime == nil {
		var ret time.Time
		return ret
	}
	return *o.EndTime
}

// GetEndTimeOk returns a tuple with the EndTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Campaign) GetEndTimeOk() (*time.Time, bool) {
	if o == nil || o.EndTime == nil {
		return nil, false
	}
	return o.EndTime, true
}

// HasEndTime returns a boolean if a field has been set.
func (o *Campaign) HasEndTime() bool {
	if o != nil && o.EndTime != nil {
		return true
	}

	return false
}

// SetEndTime gets a reference to the given time.Time and assigns it to the EndTime field.
func (o *Campaign) SetEndTime(v time.Time) {
	o.EndTime = &v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *Campaign) GetAttributes() map[string]interface{} {
	if o == nil || o.Attributes == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Campaign) GetAttributesOk() (map[string]interface{}, bool) {
	if o == nil || o.Attributes == nil {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *Campaign) HasAttributes() bool {
	if o != nil && o.Attributes != nil {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given map[string]interface{} and assigns it to the Attributes field.
func (o *Campaign) SetAttributes(v map[string]interface{}) {
	o.Attributes = v
}

// GetState returns the State field value
func (o *Campaign) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *Campaign) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *Campaign) SetState(v string) {
	o.State = v
}

// GetActiveRulesetId returns the ActiveRulesetId field value if set, zero value otherwise.
func (o *Campaign) GetActiveRulesetId() int32 {
	if o == nil || o.ActiveRulesetId == nil {
		var ret int32
		return ret
	}
	return *o.ActiveRulesetId
}

// GetActiveRulesetIdOk returns a tuple with the ActiveRulesetId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Campaign) GetActiveRulesetIdOk() (*int32, bool) {
	if o == nil || o.ActiveRulesetId == nil {
		return nil, false
	}
	return o.ActiveRulesetId, true
}

// HasActiveRulesetId returns a boolean if a field has been set.
func (o *Campaign) HasActiveRulesetId() bool {
	if o != nil && o.ActiveRulesetId != nil {
		return true
	}

	return false
}

// SetActiveRulesetId gets a reference to the given int32 and assigns it to the ActiveRulesetId field.
func (o *Campaign) SetActiveRulesetId(v int32) {
	o.ActiveRulesetId = &v
}

// GetTags returns the Tags field value
func (o *Campaign) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *Campaign) GetTagsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tags, true
}

// SetTags sets field value
func (o *Campaign) SetTags(v []string) {
	o.Tags = v
}

// GetFeatures returns the Features field value
func (o *Campaign) GetFeatures() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Features
}

// GetFeaturesOk returns a tuple with the Features field value
// and a boolean to check if the value has been set.
func (o *Campaign) GetFeaturesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Features, true
}

// SetFeatures sets field value
func (o *Campaign) SetFeatures(v []string) {
	o.Features = v
}

// GetCouponSettings returns the CouponSettings field value if set, zero value otherwise.
func (o *Campaign) GetCouponSettings() CodeGeneratorSettings {
	if o == nil || o.CouponSettings == nil {
		var ret CodeGeneratorSettings
		return ret
	}
	return *o.CouponSettings
}

// GetCouponSettingsOk returns a tuple with the CouponSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Campaign) GetCouponSettingsOk() (*CodeGeneratorSettings, bool) {
	if o == nil || o.CouponSettings == nil {
		return nil, false
	}
	return o.CouponSettings, true
}

// HasCouponSettings returns a boolean if a field has been set.
func (o *Campaign) HasCouponSettings() bool {
	if o != nil && o.CouponSettings != nil {
		return true
	}

	return false
}

// SetCouponSettings gets a reference to the given CodeGeneratorSettings and assigns it to the CouponSettings field.
func (o *Campaign) SetCouponSettings(v CodeGeneratorSettings) {
	o.CouponSettings = &v
}

// GetReferralSettings returns the ReferralSettings field value if set, zero value otherwise.
func (o *Campaign) GetReferralSettings() CodeGeneratorSettings {
	if o == nil || o.ReferralSettings == nil {
		var ret CodeGeneratorSettings
		return ret
	}
	return *o.ReferralSettings
}

// GetReferralSettingsOk returns a tuple with the ReferralSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Campaign) GetReferralSettingsOk() (*CodeGeneratorSettings, bool) {
	if o == nil || o.ReferralSettings == nil {
		return nil, false
	}
	return o.ReferralSettings, true
}

// HasReferralSettings returns a boolean if a field has been set.
func (o *Campaign) HasReferralSettings() bool {
	if o != nil && o.ReferralSettings != nil {
		return true
	}

	return false
}

// SetReferralSettings gets a reference to the given CodeGeneratorSettings and assigns it to the ReferralSettings field.
func (o *Campaign) SetReferralSettings(v CodeGeneratorSettings) {
	o.ReferralSettings = &v
}

// GetLimits returns the Limits field value
func (o *Campaign) GetLimits() []LimitConfig {
	if o == nil {
		var ret []LimitConfig
		return ret
	}

	return o.Limits
}

// GetLimitsOk returns a tuple with the Limits field value
// and a boolean to check if the value has been set.
func (o *Campaign) GetLimitsOk() ([]LimitConfig, bool) {
	if o == nil {
		return nil, false
	}
	return o.Limits, true
}

// SetLimits sets field value
func (o *Campaign) SetLimits(v []LimitConfig) {
	o.Limits = v
}

// GetCampaignGroups returns the CampaignGroups field value if set, zero value otherwise.
func (o *Campaign) GetCampaignGroups() []int32 {
	if o == nil || o.CampaignGroups == nil {
		var ret []int32
		return ret
	}
	return o.CampaignGroups
}

// GetCampaignGroupsOk returns a tuple with the CampaignGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Campaign) GetCampaignGroupsOk() ([]int32, bool) {
	if o == nil || o.CampaignGroups == nil {
		return nil, false
	}
	return o.CampaignGroups, true
}

// HasCampaignGroups returns a boolean if a field has been set.
func (o *Campaign) HasCampaignGroups() bool {
	if o != nil && o.CampaignGroups != nil {
		return true
	}

	return false
}

// SetCampaignGroups gets a reference to the given []int32 and assigns it to the CampaignGroups field.
func (o *Campaign) SetCampaignGroups(v []int32) {
	o.CampaignGroups = v
}

// GetCouponRedemptionCount returns the CouponRedemptionCount field value if set, zero value otherwise.
func (o *Campaign) GetCouponRedemptionCount() int32 {
	if o == nil || o.CouponRedemptionCount == nil {
		var ret int32
		return ret
	}
	return *o.CouponRedemptionCount
}

// GetCouponRedemptionCountOk returns a tuple with the CouponRedemptionCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Campaign) GetCouponRedemptionCountOk() (*int32, bool) {
	if o == nil || o.CouponRedemptionCount == nil {
		return nil, false
	}
	return o.CouponRedemptionCount, true
}

// HasCouponRedemptionCount returns a boolean if a field has been set.
func (o *Campaign) HasCouponRedemptionCount() bool {
	if o != nil && o.CouponRedemptionCount != nil {
		return true
	}

	return false
}

// SetCouponRedemptionCount gets a reference to the given int32 and assigns it to the CouponRedemptionCount field.
func (o *Campaign) SetCouponRedemptionCount(v int32) {
	o.CouponRedemptionCount = &v
}

// GetReferralRedemptionCount returns the ReferralRedemptionCount field value if set, zero value otherwise.
func (o *Campaign) GetReferralRedemptionCount() int32 {
	if o == nil || o.ReferralRedemptionCount == nil {
		var ret int32
		return ret
	}
	return *o.ReferralRedemptionCount
}

// GetReferralRedemptionCountOk returns a tuple with the ReferralRedemptionCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Campaign) GetReferralRedemptionCountOk() (*int32, bool) {
	if o == nil || o.ReferralRedemptionCount == nil {
		return nil, false
	}
	return o.ReferralRedemptionCount, true
}

// HasReferralRedemptionCount returns a boolean if a field has been set.
func (o *Campaign) HasReferralRedemptionCount() bool {
	if o != nil && o.ReferralRedemptionCount != nil {
		return true
	}

	return false
}

// SetReferralRedemptionCount gets a reference to the given int32 and assigns it to the ReferralRedemptionCount field.
func (o *Campaign) SetReferralRedemptionCount(v int32) {
	o.ReferralRedemptionCount = &v
}

// GetDiscountCount returns the DiscountCount field value if set, zero value otherwise.
func (o *Campaign) GetDiscountCount() float32 {
	if o == nil || o.DiscountCount == nil {
		var ret float32
		return ret
	}
	return *o.DiscountCount
}

// GetDiscountCountOk returns a tuple with the DiscountCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Campaign) GetDiscountCountOk() (*float32, bool) {
	if o == nil || o.DiscountCount == nil {
		return nil, false
	}
	return o.DiscountCount, true
}

// HasDiscountCount returns a boolean if a field has been set.
func (o *Campaign) HasDiscountCount() bool {
	if o != nil && o.DiscountCount != nil {
		return true
	}

	return false
}

// SetDiscountCount gets a reference to the given float32 and assigns it to the DiscountCount field.
func (o *Campaign) SetDiscountCount(v float32) {
	o.DiscountCount = &v
}

// GetDiscountEffectCount returns the DiscountEffectCount field value if set, zero value otherwise.
func (o *Campaign) GetDiscountEffectCount() int32 {
	if o == nil || o.DiscountEffectCount == nil {
		var ret int32
		return ret
	}
	return *o.DiscountEffectCount
}

// GetDiscountEffectCountOk returns a tuple with the DiscountEffectCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Campaign) GetDiscountEffectCountOk() (*int32, bool) {
	if o == nil || o.DiscountEffectCount == nil {
		return nil, false
	}
	return o.DiscountEffectCount, true
}

// HasDiscountEffectCount returns a boolean if a field has been set.
func (o *Campaign) HasDiscountEffectCount() bool {
	if o != nil && o.DiscountEffectCount != nil {
		return true
	}

	return false
}

// SetDiscountEffectCount gets a reference to the given int32 and assigns it to the DiscountEffectCount field.
func (o *Campaign) SetDiscountEffectCount(v int32) {
	o.DiscountEffectCount = &v
}

// GetCouponCreationCount returns the CouponCreationCount field value if set, zero value otherwise.
func (o *Campaign) GetCouponCreationCount() int32 {
	if o == nil || o.CouponCreationCount == nil {
		var ret int32
		return ret
	}
	return *o.CouponCreationCount
}

// GetCouponCreationCountOk returns a tuple with the CouponCreationCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Campaign) GetCouponCreationCountOk() (*int32, bool) {
	if o == nil || o.CouponCreationCount == nil {
		return nil, false
	}
	return o.CouponCreationCount, true
}

// HasCouponCreationCount returns a boolean if a field has been set.
func (o *Campaign) HasCouponCreationCount() bool {
	if o != nil && o.CouponCreationCount != nil {
		return true
	}

	return false
}

// SetCouponCreationCount gets a reference to the given int32 and assigns it to the CouponCreationCount field.
func (o *Campaign) SetCouponCreationCount(v int32) {
	o.CouponCreationCount = &v
}

// GetCustomEffectCount returns the CustomEffectCount field value if set, zero value otherwise.
func (o *Campaign) GetCustomEffectCount() int32 {
	if o == nil || o.CustomEffectCount == nil {
		var ret int32
		return ret
	}
	return *o.CustomEffectCount
}

// GetCustomEffectCountOk returns a tuple with the CustomEffectCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Campaign) GetCustomEffectCountOk() (*int32, bool) {
	if o == nil || o.CustomEffectCount == nil {
		return nil, false
	}
	return o.CustomEffectCount, true
}

// HasCustomEffectCount returns a boolean if a field has been set.
func (o *Campaign) HasCustomEffectCount() bool {
	if o != nil && o.CustomEffectCount != nil {
		return true
	}

	return false
}

// SetCustomEffectCount gets a reference to the given int32 and assigns it to the CustomEffectCount field.
func (o *Campaign) SetCustomEffectCount(v int32) {
	o.CustomEffectCount = &v
}

// GetReferralCreationCount returns the ReferralCreationCount field value if set, zero value otherwise.
func (o *Campaign) GetReferralCreationCount() int32 {
	if o == nil || o.ReferralCreationCount == nil {
		var ret int32
		return ret
	}
	return *o.ReferralCreationCount
}

// GetReferralCreationCountOk returns a tuple with the ReferralCreationCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Campaign) GetReferralCreationCountOk() (*int32, bool) {
	if o == nil || o.ReferralCreationCount == nil {
		return nil, false
	}
	return o.ReferralCreationCount, true
}

// HasReferralCreationCount returns a boolean if a field has been set.
func (o *Campaign) HasReferralCreationCount() bool {
	if o != nil && o.ReferralCreationCount != nil {
		return true
	}

	return false
}

// SetReferralCreationCount gets a reference to the given int32 and assigns it to the ReferralCreationCount field.
func (o *Campaign) SetReferralCreationCount(v int32) {
	o.ReferralCreationCount = &v
}

// GetAddFreeItemEffectCount returns the AddFreeItemEffectCount field value if set, zero value otherwise.
func (o *Campaign) GetAddFreeItemEffectCount() int32 {
	if o == nil || o.AddFreeItemEffectCount == nil {
		var ret int32
		return ret
	}
	return *o.AddFreeItemEffectCount
}

// GetAddFreeItemEffectCountOk returns a tuple with the AddFreeItemEffectCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Campaign) GetAddFreeItemEffectCountOk() (*int32, bool) {
	if o == nil || o.AddFreeItemEffectCount == nil {
		return nil, false
	}
	return o.AddFreeItemEffectCount, true
}

// HasAddFreeItemEffectCount returns a boolean if a field has been set.
func (o *Campaign) HasAddFreeItemEffectCount() bool {
	if o != nil && o.AddFreeItemEffectCount != nil {
		return true
	}

	return false
}

// SetAddFreeItemEffectCount gets a reference to the given int32 and assigns it to the AddFreeItemEffectCount field.
func (o *Campaign) SetAddFreeItemEffectCount(v int32) {
	o.AddFreeItemEffectCount = &v
}

// GetAwardedGiveawaysCount returns the AwardedGiveawaysCount field value if set, zero value otherwise.
func (o *Campaign) GetAwardedGiveawaysCount() int32 {
	if o == nil || o.AwardedGiveawaysCount == nil {
		var ret int32
		return ret
	}
	return *o.AwardedGiveawaysCount
}

// GetAwardedGiveawaysCountOk returns a tuple with the AwardedGiveawaysCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Campaign) GetAwardedGiveawaysCountOk() (*int32, bool) {
	if o == nil || o.AwardedGiveawaysCount == nil {
		return nil, false
	}
	return o.AwardedGiveawaysCount, true
}

// HasAwardedGiveawaysCount returns a boolean if a field has been set.
func (o *Campaign) HasAwardedGiveawaysCount() bool {
	if o != nil && o.AwardedGiveawaysCount != nil {
		return true
	}

	return false
}

// SetAwardedGiveawaysCount gets a reference to the given int32 and assigns it to the AwardedGiveawaysCount field.
func (o *Campaign) SetAwardedGiveawaysCount(v int32) {
	o.AwardedGiveawaysCount = &v
}

// GetCreatedLoyaltyPointsCount returns the CreatedLoyaltyPointsCount field value if set, zero value otherwise.
func (o *Campaign) GetCreatedLoyaltyPointsCount() float32 {
	if o == nil || o.CreatedLoyaltyPointsCount == nil {
		var ret float32
		return ret
	}
	return *o.CreatedLoyaltyPointsCount
}

// GetCreatedLoyaltyPointsCountOk returns a tuple with the CreatedLoyaltyPointsCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Campaign) GetCreatedLoyaltyPointsCountOk() (*float32, bool) {
	if o == nil || o.CreatedLoyaltyPointsCount == nil {
		return nil, false
	}
	return o.CreatedLoyaltyPointsCount, true
}

// HasCreatedLoyaltyPointsCount returns a boolean if a field has been set.
func (o *Campaign) HasCreatedLoyaltyPointsCount() bool {
	if o != nil && o.CreatedLoyaltyPointsCount != nil {
		return true
	}

	return false
}

// SetCreatedLoyaltyPointsCount gets a reference to the given float32 and assigns it to the CreatedLoyaltyPointsCount field.
func (o *Campaign) SetCreatedLoyaltyPointsCount(v float32) {
	o.CreatedLoyaltyPointsCount = &v
}

// GetCreatedLoyaltyPointsEffectCount returns the CreatedLoyaltyPointsEffectCount field value if set, zero value otherwise.
func (o *Campaign) GetCreatedLoyaltyPointsEffectCount() int32 {
	if o == nil || o.CreatedLoyaltyPointsEffectCount == nil {
		var ret int32
		return ret
	}
	return *o.CreatedLoyaltyPointsEffectCount
}

// GetCreatedLoyaltyPointsEffectCountOk returns a tuple with the CreatedLoyaltyPointsEffectCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Campaign) GetCreatedLoyaltyPointsEffectCountOk() (*int32, bool) {
	if o == nil || o.CreatedLoyaltyPointsEffectCount == nil {
		return nil, false
	}
	return o.CreatedLoyaltyPointsEffectCount, true
}

// HasCreatedLoyaltyPointsEffectCount returns a boolean if a field has been set.
func (o *Campaign) HasCreatedLoyaltyPointsEffectCount() bool {
	if o != nil && o.CreatedLoyaltyPointsEffectCount != nil {
		return true
	}

	return false
}

// SetCreatedLoyaltyPointsEffectCount gets a reference to the given int32 and assigns it to the CreatedLoyaltyPointsEffectCount field.
func (o *Campaign) SetCreatedLoyaltyPointsEffectCount(v int32) {
	o.CreatedLoyaltyPointsEffectCount = &v
}

// GetRedeemedLoyaltyPointsCount returns the RedeemedLoyaltyPointsCount field value if set, zero value otherwise.
func (o *Campaign) GetRedeemedLoyaltyPointsCount() float32 {
	if o == nil || o.RedeemedLoyaltyPointsCount == nil {
		var ret float32
		return ret
	}
	return *o.RedeemedLoyaltyPointsCount
}

// GetRedeemedLoyaltyPointsCountOk returns a tuple with the RedeemedLoyaltyPointsCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Campaign) GetRedeemedLoyaltyPointsCountOk() (*float32, bool) {
	if o == nil || o.RedeemedLoyaltyPointsCount == nil {
		return nil, false
	}
	return o.RedeemedLoyaltyPointsCount, true
}

// HasRedeemedLoyaltyPointsCount returns a boolean if a field has been set.
func (o *Campaign) HasRedeemedLoyaltyPointsCount() bool {
	if o != nil && o.RedeemedLoyaltyPointsCount != nil {
		return true
	}

	return false
}

// SetRedeemedLoyaltyPointsCount gets a reference to the given float32 and assigns it to the RedeemedLoyaltyPointsCount field.
func (o *Campaign) SetRedeemedLoyaltyPointsCount(v float32) {
	o.RedeemedLoyaltyPointsCount = &v
}

// GetRedeemedLoyaltyPointsEffectCount returns the RedeemedLoyaltyPointsEffectCount field value if set, zero value otherwise.
func (o *Campaign) GetRedeemedLoyaltyPointsEffectCount() int32 {
	if o == nil || o.RedeemedLoyaltyPointsEffectCount == nil {
		var ret int32
		return ret
	}
	return *o.RedeemedLoyaltyPointsEffectCount
}

// GetRedeemedLoyaltyPointsEffectCountOk returns a tuple with the RedeemedLoyaltyPointsEffectCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Campaign) GetRedeemedLoyaltyPointsEffectCountOk() (*int32, bool) {
	if o == nil || o.RedeemedLoyaltyPointsEffectCount == nil {
		return nil, false
	}
	return o.RedeemedLoyaltyPointsEffectCount, true
}

// HasRedeemedLoyaltyPointsEffectCount returns a boolean if a field has been set.
func (o *Campaign) HasRedeemedLoyaltyPointsEffectCount() bool {
	if o != nil && o.RedeemedLoyaltyPointsEffectCount != nil {
		return true
	}

	return false
}

// SetRedeemedLoyaltyPointsEffectCount gets a reference to the given int32 and assigns it to the RedeemedLoyaltyPointsEffectCount field.
func (o *Campaign) SetRedeemedLoyaltyPointsEffectCount(v int32) {
	o.RedeemedLoyaltyPointsEffectCount = &v
}

// GetCallApiEffectCount returns the CallApiEffectCount field value if set, zero value otherwise.
func (o *Campaign) GetCallApiEffectCount() int32 {
	if o == nil || o.CallApiEffectCount == nil {
		var ret int32
		return ret
	}
	return *o.CallApiEffectCount
}

// GetCallApiEffectCountOk returns a tuple with the CallApiEffectCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Campaign) GetCallApiEffectCountOk() (*int32, bool) {
	if o == nil || o.CallApiEffectCount == nil {
		return nil, false
	}
	return o.CallApiEffectCount, true
}

// HasCallApiEffectCount returns a boolean if a field has been set.
func (o *Campaign) HasCallApiEffectCount() bool {
	if o != nil && o.CallApiEffectCount != nil {
		return true
	}

	return false
}

// SetCallApiEffectCount gets a reference to the given int32 and assigns it to the CallApiEffectCount field.
func (o *Campaign) SetCallApiEffectCount(v int32) {
	o.CallApiEffectCount = &v
}

// GetLastActivity returns the LastActivity field value if set, zero value otherwise.
func (o *Campaign) GetLastActivity() time.Time {
	if o == nil || o.LastActivity == nil {
		var ret time.Time
		return ret
	}
	return *o.LastActivity
}

// GetLastActivityOk returns a tuple with the LastActivity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Campaign) GetLastActivityOk() (*time.Time, bool) {
	if o == nil || o.LastActivity == nil {
		return nil, false
	}
	return o.LastActivity, true
}

// HasLastActivity returns a boolean if a field has been set.
func (o *Campaign) HasLastActivity() bool {
	if o != nil && o.LastActivity != nil {
		return true
	}

	return false
}

// SetLastActivity gets a reference to the given time.Time and assigns it to the LastActivity field.
func (o *Campaign) SetLastActivity(v time.Time) {
	o.LastActivity = &v
}

// GetUpdated returns the Updated field value if set, zero value otherwise.
func (o *Campaign) GetUpdated() time.Time {
	if o == nil || o.Updated == nil {
		var ret time.Time
		return ret
	}
	return *o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Campaign) GetUpdatedOk() (*time.Time, bool) {
	if o == nil || o.Updated == nil {
		return nil, false
	}
	return o.Updated, true
}

// HasUpdated returns a boolean if a field has been set.
func (o *Campaign) HasUpdated() bool {
	if o != nil && o.Updated != nil {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given time.Time and assigns it to the Updated field.
func (o *Campaign) SetUpdated(v time.Time) {
	o.Updated = &v
}

// GetCreatedBy returns the CreatedBy field value if set, zero value otherwise.
func (o *Campaign) GetCreatedBy() string {
	if o == nil || o.CreatedBy == nil {
		var ret string
		return ret
	}
	return *o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Campaign) GetCreatedByOk() (*string, bool) {
	if o == nil || o.CreatedBy == nil {
		return nil, false
	}
	return o.CreatedBy, true
}

// HasCreatedBy returns a boolean if a field has been set.
func (o *Campaign) HasCreatedBy() bool {
	if o != nil && o.CreatedBy != nil {
		return true
	}

	return false
}

// SetCreatedBy gets a reference to the given string and assigns it to the CreatedBy field.
func (o *Campaign) SetCreatedBy(v string) {
	o.CreatedBy = &v
}

// GetUpdatedBy returns the UpdatedBy field value if set, zero value otherwise.
func (o *Campaign) GetUpdatedBy() string {
	if o == nil || o.UpdatedBy == nil {
		var ret string
		return ret
	}
	return *o.UpdatedBy
}

// GetUpdatedByOk returns a tuple with the UpdatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Campaign) GetUpdatedByOk() (*string, bool) {
	if o == nil || o.UpdatedBy == nil {
		return nil, false
	}
	return o.UpdatedBy, true
}

// HasUpdatedBy returns a boolean if a field has been set.
func (o *Campaign) HasUpdatedBy() bool {
	if o != nil && o.UpdatedBy != nil {
		return true
	}

	return false
}

// SetUpdatedBy gets a reference to the given string and assigns it to the UpdatedBy field.
func (o *Campaign) SetUpdatedBy(v string) {
	o.UpdatedBy = &v
}

// GetTemplateId returns the TemplateId field value if set, zero value otherwise.
func (o *Campaign) GetTemplateId() int32 {
	if o == nil || o.TemplateId == nil {
		var ret int32
		return ret
	}
	return *o.TemplateId
}

// GetTemplateIdOk returns a tuple with the TemplateId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Campaign) GetTemplateIdOk() (*int32, bool) {
	if o == nil || o.TemplateId == nil {
		return nil, false
	}
	return o.TemplateId, true
}

// HasTemplateId returns a boolean if a field has been set.
func (o *Campaign) HasTemplateId() bool {
	if o != nil && o.TemplateId != nil {
		return true
	}

	return false
}

// SetTemplateId gets a reference to the given int32 and assigns it to the TemplateId field.
func (o *Campaign) SetTemplateId(v int32) {
	o.TemplateId = &v
}

func (o Campaign) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["created"] = o.Created
	}
	if true {
		toSerialize["applicationId"] = o.ApplicationId
	}
	if true {
		toSerialize["userId"] = o.UserId
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["description"] = o.Description
	}
	if o.StartTime != nil {
		toSerialize["startTime"] = o.StartTime
	}
	if o.EndTime != nil {
		toSerialize["endTime"] = o.EndTime
	}
	if o.Attributes != nil {
		toSerialize["attributes"] = o.Attributes
	}
	if true {
		toSerialize["state"] = o.State
	}
	if o.ActiveRulesetId != nil {
		toSerialize["activeRulesetId"] = o.ActiveRulesetId
	}
	if true {
		toSerialize["tags"] = o.Tags
	}
	if true {
		toSerialize["features"] = o.Features
	}
	if o.CouponSettings != nil {
		toSerialize["couponSettings"] = o.CouponSettings
	}
	if o.ReferralSettings != nil {
		toSerialize["referralSettings"] = o.ReferralSettings
	}
	if true {
		toSerialize["limits"] = o.Limits
	}
	if o.CampaignGroups != nil {
		toSerialize["campaignGroups"] = o.CampaignGroups
	}
	if o.CouponRedemptionCount != nil {
		toSerialize["couponRedemptionCount"] = o.CouponRedemptionCount
	}
	if o.ReferralRedemptionCount != nil {
		toSerialize["referralRedemptionCount"] = o.ReferralRedemptionCount
	}
	if o.DiscountCount != nil {
		toSerialize["discountCount"] = o.DiscountCount
	}
	if o.DiscountEffectCount != nil {
		toSerialize["discountEffectCount"] = o.DiscountEffectCount
	}
	if o.CouponCreationCount != nil {
		toSerialize["couponCreationCount"] = o.CouponCreationCount
	}
	if o.CustomEffectCount != nil {
		toSerialize["customEffectCount"] = o.CustomEffectCount
	}
	if o.ReferralCreationCount != nil {
		toSerialize["referralCreationCount"] = o.ReferralCreationCount
	}
	if o.AddFreeItemEffectCount != nil {
		toSerialize["addFreeItemEffectCount"] = o.AddFreeItemEffectCount
	}
	if o.AwardedGiveawaysCount != nil {
		toSerialize["awardedGiveawaysCount"] = o.AwardedGiveawaysCount
	}
	if o.CreatedLoyaltyPointsCount != nil {
		toSerialize["createdLoyaltyPointsCount"] = o.CreatedLoyaltyPointsCount
	}
	if o.CreatedLoyaltyPointsEffectCount != nil {
		toSerialize["createdLoyaltyPointsEffectCount"] = o.CreatedLoyaltyPointsEffectCount
	}
	if o.RedeemedLoyaltyPointsCount != nil {
		toSerialize["redeemedLoyaltyPointsCount"] = o.RedeemedLoyaltyPointsCount
	}
	if o.RedeemedLoyaltyPointsEffectCount != nil {
		toSerialize["redeemedLoyaltyPointsEffectCount"] = o.RedeemedLoyaltyPointsEffectCount
	}
	if o.CallApiEffectCount != nil {
		toSerialize["callApiEffectCount"] = o.CallApiEffectCount
	}
	if o.LastActivity != nil {
		toSerialize["lastActivity"] = o.LastActivity
	}
	if o.Updated != nil {
		toSerialize["updated"] = o.Updated
	}
	if o.CreatedBy != nil {
		toSerialize["createdBy"] = o.CreatedBy
	}
	if o.UpdatedBy != nil {
		toSerialize["updatedBy"] = o.UpdatedBy
	}
	if o.TemplateId != nil {
		toSerialize["templateId"] = o.TemplateId
	}
	return json.Marshal(toSerialize)
}

type NullableCampaign struct {
	value *Campaign
	isSet bool
}

func (v NullableCampaign) Get() *Campaign {
	return v.value
}

func (v *NullableCampaign) Set(val *Campaign) {
	v.value = val
	v.isSet = true
}

func (v NullableCampaign) IsSet() bool {
	return v.isSet
}

func (v *NullableCampaign) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCampaign(val *Campaign) *NullableCampaign {
	return &NullableCampaign{value: val, isSet: true}
}

func (v NullableCampaign) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCampaign) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


