/*
Integration API reference docs

Use the Integration API to push data to and retrieve data from Talon.One in real time. For more background information about this API, see [Integration API overview](/docs/dev/integration-api/overview)  For example, use this API to share shopping cart information as a session with Talon.One and evaluate promotion rules. You can also create custom events to track specific actions that do not fit into the session data model.  Ensure you [authenticate](#section/Authentication) to make requests to the API.  <div class=\"redoc-section\">   <p class=\"title\">Are you looking for a different API?</p>    If you need the API to:    - Interact with the Campaign Manager for backoffice operations, see [the Management API reference docs](https://docs.talon.one/management-api).   - Integrate with Talon.One from a CEP or CDP platform, see [the Third-party API reference docs](https://docs.talon.one/third-party-api).  </div>  # Authentication  <SecurityDefinitions /> 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
	"time"
)

// UpdateCouponBatch 
type UpdateCouponBatch struct {
	// The number of times the coupon code can be redeemed. `0` means unlimited redemptions but any campaign usage limits will still apply. 
	UsageLimit *int32 `json:"usageLimit,omitempty"`
	// The amount of discounts that can be given with this coupon code. 
	DiscountLimit *float32 `json:"discountLimit,omitempty"`
	// Timestamp at which point the coupon becomes valid.
	StartDate *time.Time `json:"startDate,omitempty"`
	// Expiry date of the coupon. Coupon never expires if this is omitted, zero, or negative.
	ExpiryDate *time.Time `json:"expiryDate,omitempty"`
	// Arbitrary properties associated with this item.
	Attributes map[string]interface{} `json:"attributes,omitempty"`
	// The id of the batch the coupon belongs to.
	BatchID *string `json:"batchID,omitempty"`
}

// NewUpdateCouponBatch instantiates a new UpdateCouponBatch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateCouponBatch() *UpdateCouponBatch {
	this := UpdateCouponBatch{}
	return &this
}

// NewUpdateCouponBatchWithDefaults instantiates a new UpdateCouponBatch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateCouponBatchWithDefaults() *UpdateCouponBatch {
	this := UpdateCouponBatch{}
	return &this
}

// GetUsageLimit returns the UsageLimit field value if set, zero value otherwise.
func (o *UpdateCouponBatch) GetUsageLimit() int32 {
	if o == nil || o.UsageLimit == nil {
		var ret int32
		return ret
	}
	return *o.UsageLimit
}

// GetUsageLimitOk returns a tuple with the UsageLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCouponBatch) GetUsageLimitOk() (*int32, bool) {
	if o == nil || o.UsageLimit == nil {
		return nil, false
	}
	return o.UsageLimit, true
}

// HasUsageLimit returns a boolean if a field has been set.
func (o *UpdateCouponBatch) HasUsageLimit() bool {
	if o != nil && o.UsageLimit != nil {
		return true
	}

	return false
}

// SetUsageLimit gets a reference to the given int32 and assigns it to the UsageLimit field.
func (o *UpdateCouponBatch) SetUsageLimit(v int32) {
	o.UsageLimit = &v
}

// GetDiscountLimit returns the DiscountLimit field value if set, zero value otherwise.
func (o *UpdateCouponBatch) GetDiscountLimit() float32 {
	if o == nil || o.DiscountLimit == nil {
		var ret float32
		return ret
	}
	return *o.DiscountLimit
}

// GetDiscountLimitOk returns a tuple with the DiscountLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCouponBatch) GetDiscountLimitOk() (*float32, bool) {
	if o == nil || o.DiscountLimit == nil {
		return nil, false
	}
	return o.DiscountLimit, true
}

// HasDiscountLimit returns a boolean if a field has been set.
func (o *UpdateCouponBatch) HasDiscountLimit() bool {
	if o != nil && o.DiscountLimit != nil {
		return true
	}

	return false
}

// SetDiscountLimit gets a reference to the given float32 and assigns it to the DiscountLimit field.
func (o *UpdateCouponBatch) SetDiscountLimit(v float32) {
	o.DiscountLimit = &v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise.
func (o *UpdateCouponBatch) GetStartDate() time.Time {
	if o == nil || o.StartDate == nil {
		var ret time.Time
		return ret
	}
	return *o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCouponBatch) GetStartDateOk() (*time.Time, bool) {
	if o == nil || o.StartDate == nil {
		return nil, false
	}
	return o.StartDate, true
}

// HasStartDate returns a boolean if a field has been set.
func (o *UpdateCouponBatch) HasStartDate() bool {
	if o != nil && o.StartDate != nil {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given time.Time and assigns it to the StartDate field.
func (o *UpdateCouponBatch) SetStartDate(v time.Time) {
	o.StartDate = &v
}

// GetExpiryDate returns the ExpiryDate field value if set, zero value otherwise.
func (o *UpdateCouponBatch) GetExpiryDate() time.Time {
	if o == nil || o.ExpiryDate == nil {
		var ret time.Time
		return ret
	}
	return *o.ExpiryDate
}

// GetExpiryDateOk returns a tuple with the ExpiryDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCouponBatch) GetExpiryDateOk() (*time.Time, bool) {
	if o == nil || o.ExpiryDate == nil {
		return nil, false
	}
	return o.ExpiryDate, true
}

// HasExpiryDate returns a boolean if a field has been set.
func (o *UpdateCouponBatch) HasExpiryDate() bool {
	if o != nil && o.ExpiryDate != nil {
		return true
	}

	return false
}

// SetExpiryDate gets a reference to the given time.Time and assigns it to the ExpiryDate field.
func (o *UpdateCouponBatch) SetExpiryDate(v time.Time) {
	o.ExpiryDate = &v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *UpdateCouponBatch) GetAttributes() map[string]interface{} {
	if o == nil || o.Attributes == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCouponBatch) GetAttributesOk() (map[string]interface{}, bool) {
	if o == nil || o.Attributes == nil {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *UpdateCouponBatch) HasAttributes() bool {
	if o != nil && o.Attributes != nil {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given map[string]interface{} and assigns it to the Attributes field.
func (o *UpdateCouponBatch) SetAttributes(v map[string]interface{}) {
	o.Attributes = v
}

// GetBatchID returns the BatchID field value if set, zero value otherwise.
func (o *UpdateCouponBatch) GetBatchID() string {
	if o == nil || o.BatchID == nil {
		var ret string
		return ret
	}
	return *o.BatchID
}

// GetBatchIDOk returns a tuple with the BatchID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCouponBatch) GetBatchIDOk() (*string, bool) {
	if o == nil || o.BatchID == nil {
		return nil, false
	}
	return o.BatchID, true
}

// HasBatchID returns a boolean if a field has been set.
func (o *UpdateCouponBatch) HasBatchID() bool {
	if o != nil && o.BatchID != nil {
		return true
	}

	return false
}

// SetBatchID gets a reference to the given string and assigns it to the BatchID field.
func (o *UpdateCouponBatch) SetBatchID(v string) {
	o.BatchID = &v
}

func (o UpdateCouponBatch) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.UsageLimit != nil {
		toSerialize["usageLimit"] = o.UsageLimit
	}
	if o.DiscountLimit != nil {
		toSerialize["discountLimit"] = o.DiscountLimit
	}
	if o.StartDate != nil {
		toSerialize["startDate"] = o.StartDate
	}
	if o.ExpiryDate != nil {
		toSerialize["expiryDate"] = o.ExpiryDate
	}
	if o.Attributes != nil {
		toSerialize["attributes"] = o.Attributes
	}
	if o.BatchID != nil {
		toSerialize["batchID"] = o.BatchID
	}
	return json.Marshal(toSerialize)
}

type NullableUpdateCouponBatch struct {
	value *UpdateCouponBatch
	isSet bool
}

func (v NullableUpdateCouponBatch) Get() *UpdateCouponBatch {
	return v.value
}

func (v *NullableUpdateCouponBatch) Set(val *UpdateCouponBatch) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateCouponBatch) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateCouponBatch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateCouponBatch(val *UpdateCouponBatch) *NullableUpdateCouponBatch {
	return &NullableUpdateCouponBatch{value: val, isSet: true}
}

func (v NullableUpdateCouponBatch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateCouponBatch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


