/*
Integration API reference docs

Use the Integration API to push data to and retrieve data from Talon.One in real time. For more background information about this API, see [Integration API overview](/docs/dev/integration-api/overview)  For example, use this API to share shopping cart information as a session with Talon.One and evaluate promotion rules. You can also create custom events to track specific actions that do not fit into the session data model.  Ensure you [authenticate](#section/Authentication) to make requests to the API.  <div class=\"redoc-section\">   <p class=\"title\">Are you looking for a different API?</p>    If you need the API to:    - Interact with the Campaign Manager for backoffice operations, see [the Management API reference docs](https://docs.talon.one/management-api).   - Integrate with Talon.One from a CEP or CDP platform, see [the Third-party API reference docs](https://docs.talon.one/third-party-api).  </div>  # Authentication  <SecurityDefinitions /> 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
)

// ReferralCreatedEffectProps The properties specific to the \"referralCreated\" effect. This gets triggered whenever a validated rule contained a \"create referral\" effect, and a referral code was created for a customer. See \"createdReferrals\" on the response for all details of this referral code.
type ReferralCreatedEffectProps struct {
	// The referral code that was created.
	Value string `json:"value"`
}

// NewReferralCreatedEffectProps instantiates a new ReferralCreatedEffectProps object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReferralCreatedEffectProps(value string) *ReferralCreatedEffectProps {
	this := ReferralCreatedEffectProps{}
	this.Value = value
	return &this
}

// NewReferralCreatedEffectPropsWithDefaults instantiates a new ReferralCreatedEffectProps object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReferralCreatedEffectPropsWithDefaults() *ReferralCreatedEffectProps {
	this := ReferralCreatedEffectProps{}
	return &this
}

// GetValue returns the Value field value
func (o *ReferralCreatedEffectProps) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *ReferralCreatedEffectProps) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *ReferralCreatedEffectProps) SetValue(v string) {
	o.Value = v
}

func (o ReferralCreatedEffectProps) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableReferralCreatedEffectProps struct {
	value *ReferralCreatedEffectProps
	isSet bool
}

func (v NullableReferralCreatedEffectProps) Get() *ReferralCreatedEffectProps {
	return v.value
}

func (v *NullableReferralCreatedEffectProps) Set(val *ReferralCreatedEffectProps) {
	v.value = val
	v.isSet = true
}

func (v NullableReferralCreatedEffectProps) IsSet() bool {
	return v.isSet
}

func (v *NullableReferralCreatedEffectProps) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReferralCreatedEffectProps(val *ReferralCreatedEffectProps) *NullableReferralCreatedEffectProps {
	return &NullableReferralCreatedEffectProps{value: val, isSet: true}
}

func (v NullableReferralCreatedEffectProps) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReferralCreatedEffectProps) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


