/*
Integration API reference docs

Use the Integration API to push data to and retrieve data from Talon.One in real time. For more background information about this API, see [Integration API overview](/docs/dev/integration-api/overview)  For example, use this API to share shopping cart information as a session with Talon.One and evaluate promotion rules. You can also create custom events to track specific actions that do not fit into the session data model.  Ensure you [authenticate](#section/Authentication) to make requests to the API.  <div class=\"redoc-section\">   <p class=\"title\">Are you looking for a different API?</p>    If you need the API to:    - Interact with the Campaign Manager for backoffice operations, see [the Management API reference docs](https://docs.talon.one/management-api).   - Integrate with Talon.One from a CEP or CDP platform, see [the Third-party API reference docs](https://docs.talon.one/third-party-api).  </div>  # Authentication  <SecurityDefinitions /> 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
)

// AsyncCouponCreationResponse struct for AsyncCouponCreationResponse
type AsyncCouponCreationResponse struct {
	// The batch ID that all coupons created by the request will have.
	BatchId string `json:"batchId"`
}

// NewAsyncCouponCreationResponse instantiates a new AsyncCouponCreationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAsyncCouponCreationResponse(batchId string) *AsyncCouponCreationResponse {
	this := AsyncCouponCreationResponse{}
	this.BatchId = batchId
	return &this
}

// NewAsyncCouponCreationResponseWithDefaults instantiates a new AsyncCouponCreationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAsyncCouponCreationResponseWithDefaults() *AsyncCouponCreationResponse {
	this := AsyncCouponCreationResponse{}
	return &this
}

// GetBatchId returns the BatchId field value
func (o *AsyncCouponCreationResponse) GetBatchId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BatchId
}

// GetBatchIdOk returns a tuple with the BatchId field value
// and a boolean to check if the value has been set.
func (o *AsyncCouponCreationResponse) GetBatchIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BatchId, true
}

// SetBatchId sets field value
func (o *AsyncCouponCreationResponse) SetBatchId(v string) {
	o.BatchId = v
}

func (o AsyncCouponCreationResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["batchId"] = o.BatchId
	}
	return json.Marshal(toSerialize)
}

type NullableAsyncCouponCreationResponse struct {
	value *AsyncCouponCreationResponse
	isSet bool
}

func (v NullableAsyncCouponCreationResponse) Get() *AsyncCouponCreationResponse {
	return v.value
}

func (v *NullableAsyncCouponCreationResponse) Set(val *AsyncCouponCreationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAsyncCouponCreationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAsyncCouponCreationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAsyncCouponCreationResponse(val *AsyncCouponCreationResponse) *NullableAsyncCouponCreationResponse {
	return &NullableAsyncCouponCreationResponse{value: val, isSet: true}
}

func (v NullableAsyncCouponCreationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAsyncCouponCreationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


