/*
Integration API reference docs

Use the Integration API to push data to and retrieve data from Talon.One in real time. For more background information about this API, see [Integration API overview](/docs/dev/integration-api/overview)  For example, use this API to share shopping cart information as a session with Talon.One and evaluate promotion rules. You can also create custom events to track specific actions that do not fit into the session data model.  Ensure you [authenticate](#section/Authentication) to make requests to the API.  <div class=\"redoc-section\">   <p class=\"title\">Are you looking for a different API?</p>    If you need the API to:    - Interact with the Campaign Manager for backoffice operations, see [the Management API reference docs](https://docs.talon.one/management-api).   - Integrate with Talon.One from a CEP or CDP platform, see [the Third-party API reference docs](https://docs.talon.one/third-party-api).  </div>  # Authentication  <SecurityDefinitions /> 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
)

// FuncArgDef struct for FuncArgDef
type FuncArgDef struct {
	// The type of value this argument expects.
	Type string `json:"type"`
	// A campaigner-friendly description of the argument, this will also be shown in the rule editor.
	Description string `json:"description"`
}

// NewFuncArgDef instantiates a new FuncArgDef object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFuncArgDef(type_ string, description string) *FuncArgDef {
	this := FuncArgDef{}
	this.Type = type_
	this.Description = description
	return &this
}

// NewFuncArgDefWithDefaults instantiates a new FuncArgDef object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFuncArgDefWithDefaults() *FuncArgDef {
	this := FuncArgDef{}
	return &this
}

// GetType returns the Type field value
func (o *FuncArgDef) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *FuncArgDef) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *FuncArgDef) SetType(v string) {
	o.Type = v
}

// GetDescription returns the Description field value
func (o *FuncArgDef) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *FuncArgDef) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *FuncArgDef) SetDescription(v string) {
	o.Description = v
}

func (o FuncArgDef) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["type"] = o.Type
	}
	if true {
		toSerialize["description"] = o.Description
	}
	return json.Marshal(toSerialize)
}

type NullableFuncArgDef struct {
	value *FuncArgDef
	isSet bool
}

func (v NullableFuncArgDef) Get() *FuncArgDef {
	return v.value
}

func (v *NullableFuncArgDef) Set(val *FuncArgDef) {
	v.value = val
	v.isSet = true
}

func (v NullableFuncArgDef) IsSet() bool {
	return v.isSet
}

func (v *NullableFuncArgDef) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFuncArgDef(val *FuncArgDef) *NullableFuncArgDef {
	return &NullableFuncArgDef{value: val, isSet: true}
}

func (v NullableFuncArgDef) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFuncArgDef) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


